# Identifiant unique du projet
# Override via env var SONAR_PROJECT_KEY
sonar.projectKey=${env.SONAR_PROJECT_KEY:-votre-projet-key}
sonar.projectName=${env.SONAR_PROJECT_NAME:-Company Management API}
sonar.projectVersion=${env.SONAR_PROJECT_VERSION:-1.0}

# Sources
sonar.sources=src/main/java
sonar.tests=src/test/java

# Langage
sonar.language=java
sonar.java.source=21

# Exclusions
sonar.exclusions=**/client/**, **/model/**, **/dto/**, **/config/**

# Rapports de couverture
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/jacocoTestReport.xml

# Rapports Checkstyle
sonar.java.checkstyle.reportPaths=build/reports/checkstyle/main.xml