/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.demo.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.demo.client.model.CrupdateWarehouse;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * CrupdatePurchase
 */
@JsonPropertyOrder({
  CrupdatePurchase.JSON_PROPERTY_ID,
  CrupdatePurchase.JSON_PROPERTY_EXPENSE_ID,
  CrupdatePurchase.JSON_PROPERTY_SUPPLIER,
  CrupdatePurchase.JSON_PROPERTY_EQUIPMENT,
  CrupdatePurchase.JSON_PROPERTY_MATERIAL,
  CrupdatePurchase.JSON_PROPERTY_QUANTITY,
  CrupdatePurchase.JSON_PROPERTY_IS_EQUIPMENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-02T14:33:34.451807204+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class CrupdatePurchase {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_EXPENSE_ID = "expense_id";
  private String expenseId;

  public static final String JSON_PROPERTY_SUPPLIER = "supplier";
  private CrupdateWarehouse supplier;

  public static final String JSON_PROPERTY_EQUIPMENT = "equipment";
  private String equipment;

  public static final String JSON_PROPERTY_MATERIAL = "material";
  private String material;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private Integer quantity;

  public static final String JSON_PROPERTY_IS_EQUIPMENT = "is_equipment";
  private Boolean isEquipment;

  public CrupdatePurchase() { 
  }

  public CrupdatePurchase id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public CrupdatePurchase expenseId(String expenseId) {
    this.expenseId = expenseId;
    return this;
  }

   /**
   * Get expenseId
   * @return expenseId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPENSE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExpenseId() {
    return expenseId;
  }


  @JsonProperty(JSON_PROPERTY_EXPENSE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpenseId(String expenseId) {
    this.expenseId = expenseId;
  }


  public CrupdatePurchase supplier(CrupdateWarehouse supplier) {
    this.supplier = supplier;
    return this;
  }

   /**
   * Get supplier
   * @return supplier
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPLIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CrupdateWarehouse getSupplier() {
    return supplier;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupplier(CrupdateWarehouse supplier) {
    this.supplier = supplier;
  }


  public CrupdatePurchase equipment(String equipment) {
    this.equipment = equipment;
    return this;
  }

   /**
   * Get equipment
   * @return equipment
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EQUIPMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEquipment() {
    return equipment;
  }


  @JsonProperty(JSON_PROPERTY_EQUIPMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEquipment(String equipment) {
    this.equipment = equipment;
  }


  public CrupdatePurchase material(String material) {
    this.material = material;
    return this;
  }

   /**
   * Get material
   * @return material
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATERIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMaterial() {
    return material;
  }


  @JsonProperty(JSON_PROPERTY_MATERIAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaterial(String material) {
    this.material = material;
  }


  public CrupdatePurchase quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  public CrupdatePurchase isEquipment(Boolean isEquipment) {
    this.isEquipment = isEquipment;
    return this;
  }

   /**
   * Get isEquipment
   * @return isEquipment
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_EQUIPMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsEquipment() {
    return isEquipment;
  }


  @JsonProperty(JSON_PROPERTY_IS_EQUIPMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsEquipment(Boolean isEquipment) {
    this.isEquipment = isEquipment;
  }


  /**
   * Return true if this CrupdatePurchase object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CrupdatePurchase crupdatePurchase = (CrupdatePurchase) o;
    return Objects.equals(this.id, crupdatePurchase.id) &&
        Objects.equals(this.expenseId, crupdatePurchase.expenseId) &&
        Objects.equals(this.supplier, crupdatePurchase.supplier) &&
        Objects.equals(this.equipment, crupdatePurchase.equipment) &&
        Objects.equals(this.material, crupdatePurchase.material) &&
        Objects.equals(this.quantity, crupdatePurchase.quantity) &&
        Objects.equals(this.isEquipment, crupdatePurchase.isEquipment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, expenseId, supplier, equipment, material, quantity, isEquipment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CrupdatePurchase {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    expenseId: ").append(toIndentedString(expenseId)).append("\n");
    sb.append("    supplier: ").append(toIndentedString(supplier)).append("\n");
    sb.append("    equipment: ").append(toIndentedString(equipment)).append("\n");
    sb.append("    material: ").append(toIndentedString(material)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    isEquipment: ").append(toIndentedString(isEquipment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `expense_id` to the URL query string
    if (getExpenseId() != null) {
      joiner.add(String.format("%sexpense_id%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExpenseId()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `supplier` to the URL query string
    if (getSupplier() != null) {
      joiner.add(getSupplier().toUrlQueryString(prefix + "supplier" + suffix));
    }

    // add `equipment` to the URL query string
    if (getEquipment() != null) {
      joiner.add(String.format("%sequipment%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEquipment()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `material` to the URL query string
    if (getMaterial() != null) {
      joiner.add(String.format("%smaterial%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMaterial()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `quantity` to the URL query string
    if (getQuantity() != null) {
      joiner.add(String.format("%squantity%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getQuantity()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `is_equipment` to the URL query string
    if (getIsEquipment() != null) {
      joiner.add(String.format("%sis_equipment%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIsEquipment()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

