/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.demo.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.demo.client.model.AuditUser;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * EmployeeLeaveConfig
 */
@JsonPropertyOrder({
  EmployeeLeaveConfig.JSON_PROPERTY_ID,
  EmployeeLeaveConfig.JSON_PROPERTY_HIRE_DATE,
  EmployeeLeaveConfig.JSON_PROPERTY_CONTRACT_TYPE,
  EmployeeLeaveConfig.JSON_PROPERTY_VACATION_DAYS_PER_MONTH,
  EmployeeLeaveConfig.JSON_PROPERTY_CREATED_AT,
  EmployeeLeaveConfig.JSON_PROPERTY_UPDATED_AT,
  EmployeeLeaveConfig.JSON_PROPERTY_CREATED_BY,
  EmployeeLeaveConfig.JSON_PROPERTY_UPDATED_BY,
  EmployeeLeaveConfig.JSON_PROPERTY_COMMENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-21T02:39:21.675435070+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class EmployeeLeaveConfig {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_HIRE_DATE = "hire_date";
  private java.time.LocalDate hireDate;

  public static final String JSON_PROPERTY_CONTRACT_TYPE = "contract_type";
  private String contractType;

  public static final String JSON_PROPERTY_VACATION_DAYS_PER_MONTH = "vacation_days_per_month";
  private BigDecimal vacationDaysPerMonth;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private java.time.Instant createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private java.time.Instant updatedAt;

  public static final String JSON_PROPERTY_CREATED_BY = "created_by";
  private AuditUser createdBy;

  public static final String JSON_PROPERTY_UPDATED_BY = "updated_by";
  private AuditUser updatedBy;

  public static final String JSON_PROPERTY_COMMENT = "comment";
  private String comment;

  public EmployeeLeaveConfig() { 
  }

  public EmployeeLeaveConfig id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public EmployeeLeaveConfig hireDate(java.time.LocalDate hireDate) {
    this.hireDate = hireDate;
    return this;
  }

   /**
   * Get hireDate
   * @return hireDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HIRE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.LocalDate getHireDate() {
    return hireDate;
  }


  @JsonProperty(JSON_PROPERTY_HIRE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHireDate(java.time.LocalDate hireDate) {
    this.hireDate = hireDate;
  }


  public EmployeeLeaveConfig contractType(String contractType) {
    this.contractType = contractType;
    return this;
  }

   /**
   * Get contractType
   * @return contractType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTRACT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContractType() {
    return contractType;
  }


  @JsonProperty(JSON_PROPERTY_CONTRACT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContractType(String contractType) {
    this.contractType = contractType;
  }


  public EmployeeLeaveConfig vacationDaysPerMonth(BigDecimal vacationDaysPerMonth) {
    this.vacationDaysPerMonth = vacationDaysPerMonth;
    return this;
  }

   /**
   * Get vacationDaysPerMonth
   * @return vacationDaysPerMonth
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VACATION_DAYS_PER_MONTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getVacationDaysPerMonth() {
    return vacationDaysPerMonth;
  }


  @JsonProperty(JSON_PROPERTY_VACATION_DAYS_PER_MONTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVacationDaysPerMonth(BigDecimal vacationDaysPerMonth) {
    this.vacationDaysPerMonth = vacationDaysPerMonth;
  }


  public EmployeeLeaveConfig createdAt(java.time.Instant createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(java.time.Instant createdAt) {
    this.createdAt = createdAt;
  }


  public EmployeeLeaveConfig updatedAt(java.time.Instant updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.Instant getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(java.time.Instant updatedAt) {
    this.updatedAt = updatedAt;
  }


  public EmployeeLeaveConfig createdBy(AuditUser createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditUser getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedBy(AuditUser createdBy) {
    this.createdBy = createdBy;
  }


  public EmployeeLeaveConfig updatedBy(AuditUser updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * Get updatedBy
   * @return updatedBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditUser getUpdatedBy() {
    return updatedBy;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedBy(AuditUser updatedBy) {
    this.updatedBy = updatedBy;
  }


  public EmployeeLeaveConfig comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComment() {
    return comment;
  }


  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComment(String comment) {
    this.comment = comment;
  }


  /**
   * Return true if this EmployeeLeaveConfig object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeeLeaveConfig employeeLeaveConfig = (EmployeeLeaveConfig) o;
    return Objects.equals(this.id, employeeLeaveConfig.id) &&
        Objects.equals(this.hireDate, employeeLeaveConfig.hireDate) &&
        Objects.equals(this.contractType, employeeLeaveConfig.contractType) &&
        Objects.equals(this.vacationDaysPerMonth, employeeLeaveConfig.vacationDaysPerMonth) &&
        Objects.equals(this.createdAt, employeeLeaveConfig.createdAt) &&
        Objects.equals(this.updatedAt, employeeLeaveConfig.updatedAt) &&
        Objects.equals(this.createdBy, employeeLeaveConfig.createdBy) &&
        Objects.equals(this.updatedBy, employeeLeaveConfig.updatedBy) &&
        Objects.equals(this.comment, employeeLeaveConfig.comment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, hireDate, contractType, vacationDaysPerMonth, createdAt, updatedAt, createdBy, updatedBy, comment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeeLeaveConfig {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    hireDate: ").append(toIndentedString(hireDate)).append("\n");
    sb.append("    contractType: ").append(toIndentedString(contractType)).append("\n");
    sb.append("    vacationDaysPerMonth: ").append(toIndentedString(vacationDaysPerMonth)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format("%screated_at%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `updated_at` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format("%supdated_at%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUpdatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `created_by` to the URL query string
    if (getCreatedBy() != null) {
      joiner.add(getCreatedBy().toUrlQueryString(prefix + "created_by" + suffix));
    }

    // add `updated_by` to the URL query string
    if (getUpdatedBy() != null) {
      joiner.add(getUpdatedBy().toUrlQueryString(prefix + "updated_by" + suffix));
    }

    // add `comment` to the URL query string
    if (getComment() != null) {
      joiner.add(String.format("%scomment%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getComment()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

