/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.demo.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets EntityType
 */
public enum EntityType {
  
  USER("USER"),
  
  COMPANY("COMPANY"),
  
  JOB("JOB"),
  
  WAREHOUSE("WAREHOUSE"),
  
  EQUIPMENT("EQUIPMENT"),
  
  MATERIAL("MATERIAL"),
  
  INCOMEMONEY("INCOMEMONEY"),
  
  EXPENSEMONEY("EXPENSEMONEY"),
  
  EMPLOYEE_PAYMENT("EMPLOYEE_PAYMENT"),
  
  TRAVEL_EXPENSE("TRAVEL_EXPENSE"),
  
  TRAVELPEOPLE("TRAVELPEOPLE"),
  
  TRAVELMATERIALS("TRAVELMATERIALS"),
  
  TRAVELEQUIPMENT("TRAVELEQUIPMENT"),
  
  PURCHASE("PURCHASE"),
  
  BANK_FEE("BANK_FEE"),
  
  OTHER_EXPENSE("OTHER_EXPENSE");

  private String value;

  EntityType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static EntityType fromValue(String value) {
    for (EntityType b : EntityType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format("%s=%s", prefix, this.toString());
  }

}

