/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.demo.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.demo.client.model.AuditUser;
import com.example.demo.client.model.UsageStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * EquipmentUsage
 */
@JsonPropertyOrder({
  EquipmentUsage.JSON_PROPERTY_ID,
  EquipmentUsage.JSON_PROPERTY_EQUIPMENT_ID,
  EquipmentUsage.JSON_PROPERTY_JOB_ID,
  EquipmentUsage.JSON_PROPERTY_START_TIME,
  EquipmentUsage.JSON_PROPERTY_END_TIME,
  EquipmentUsage.JSON_PROPERTY_SOURCE_LOCATION,
  EquipmentUsage.JSON_PROPERTY_USAGE_STATUS,
  EquipmentUsage.JSON_PROPERTY_USED_BY,
  EquipmentUsage.JSON_PROPERTY_CREATED_AT,
  EquipmentUsage.JSON_PROPERTY_UPDATED_AT,
  EquipmentUsage.JSON_PROPERTY_CREATED_BY,
  EquipmentUsage.JSON_PROPERTY_UPDATED_BY,
  EquipmentUsage.JSON_PROPERTY_COMMENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-09T16:25:55.938344943+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class EquipmentUsage {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_EQUIPMENT_ID = "equipment_id";
  private String equipmentId;

  public static final String JSON_PROPERTY_JOB_ID = "job_id";
  private String jobId;

  public static final String JSON_PROPERTY_START_TIME = "start_time";
  private java.time.Instant startTime;

  public static final String JSON_PROPERTY_END_TIME = "end_time";
  private java.time.Instant endTime;

  public static final String JSON_PROPERTY_SOURCE_LOCATION = "source_location";
  private String sourceLocation;

  public static final String JSON_PROPERTY_USAGE_STATUS = "usage_status";
  private UsageStatus usageStatus;

  public static final String JSON_PROPERTY_USED_BY = "used_by";
  private String usedBy;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private java.time.Instant createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private java.time.Instant updatedAt;

  public static final String JSON_PROPERTY_CREATED_BY = "created_by";
  private AuditUser createdBy;

  public static final String JSON_PROPERTY_UPDATED_BY = "updated_by";
  private AuditUser updatedBy;

  public static final String JSON_PROPERTY_COMMENT = "comment";
  private String comment;

  public EquipmentUsage() { 
  }

  public EquipmentUsage id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public EquipmentUsage equipmentId(String equipmentId) {
    this.equipmentId = equipmentId;
    return this;
  }

   /**
   * Get equipmentId
   * @return equipmentId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EQUIPMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEquipmentId() {
    return equipmentId;
  }


  @JsonProperty(JSON_PROPERTY_EQUIPMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEquipmentId(String equipmentId) {
    this.equipmentId = equipmentId;
  }


  public EquipmentUsage jobId(String jobId) {
    this.jobId = jobId;
    return this;
  }

   /**
   * Get jobId
   * @return jobId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJobId() {
    return jobId;
  }


  @JsonProperty(JSON_PROPERTY_JOB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJobId(String jobId) {
    this.jobId = jobId;
  }


  public EquipmentUsage startTime(java.time.Instant startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.Instant getStartTime() {
    return startTime;
  }


  @JsonProperty(JSON_PROPERTY_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartTime(java.time.Instant startTime) {
    this.startTime = startTime;
  }


  public EquipmentUsage endTime(java.time.Instant endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.Instant getEndTime() {
    return endTime;
  }


  @JsonProperty(JSON_PROPERTY_END_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndTime(java.time.Instant endTime) {
    this.endTime = endTime;
  }


  public EquipmentUsage sourceLocation(String sourceLocation) {
    this.sourceLocation = sourceLocation;
    return this;
  }

   /**
   * Get sourceLocation
   * @return sourceLocation
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceLocation() {
    return sourceLocation;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceLocation(String sourceLocation) {
    this.sourceLocation = sourceLocation;
  }


  public EquipmentUsage usageStatus(UsageStatus usageStatus) {
    this.usageStatus = usageStatus;
    return this;
  }

   /**
   * Get usageStatus
   * @return usageStatus
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USAGE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UsageStatus getUsageStatus() {
    return usageStatus;
  }


  @JsonProperty(JSON_PROPERTY_USAGE_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsageStatus(UsageStatus usageStatus) {
    this.usageStatus = usageStatus;
  }


  public EquipmentUsage usedBy(String usedBy) {
    this.usedBy = usedBy;
    return this;
  }

   /**
   * Get usedBy
   * @return usedBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsedBy() {
    return usedBy;
  }


  @JsonProperty(JSON_PROPERTY_USED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsedBy(String usedBy) {
    this.usedBy = usedBy;
  }


  public EquipmentUsage createdAt(java.time.Instant createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(java.time.Instant createdAt) {
    this.createdAt = createdAt;
  }


  public EquipmentUsage updatedAt(java.time.Instant updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.Instant getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(java.time.Instant updatedAt) {
    this.updatedAt = updatedAt;
  }


  public EquipmentUsage createdBy(AuditUser createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditUser getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedBy(AuditUser createdBy) {
    this.createdBy = createdBy;
  }


  public EquipmentUsage updatedBy(AuditUser updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * Get updatedBy
   * @return updatedBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditUser getUpdatedBy() {
    return updatedBy;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedBy(AuditUser updatedBy) {
    this.updatedBy = updatedBy;
  }


  public EquipmentUsage comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComment() {
    return comment;
  }


  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComment(String comment) {
    this.comment = comment;
  }


  /**
   * Return true if this EquipmentUsage object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EquipmentUsage equipmentUsage = (EquipmentUsage) o;
    return Objects.equals(this.id, equipmentUsage.id) &&
        Objects.equals(this.equipmentId, equipmentUsage.equipmentId) &&
        Objects.equals(this.jobId, equipmentUsage.jobId) &&
        Objects.equals(this.startTime, equipmentUsage.startTime) &&
        Objects.equals(this.endTime, equipmentUsage.endTime) &&
        Objects.equals(this.sourceLocation, equipmentUsage.sourceLocation) &&
        Objects.equals(this.usageStatus, equipmentUsage.usageStatus) &&
        Objects.equals(this.usedBy, equipmentUsage.usedBy) &&
        Objects.equals(this.createdAt, equipmentUsage.createdAt) &&
        Objects.equals(this.updatedAt, equipmentUsage.updatedAt) &&
        Objects.equals(this.createdBy, equipmentUsage.createdBy) &&
        Objects.equals(this.updatedBy, equipmentUsage.updatedBy) &&
        Objects.equals(this.comment, equipmentUsage.comment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, equipmentId, jobId, startTime, endTime, sourceLocation, usageStatus, usedBy, createdAt, updatedAt, createdBy, updatedBy, comment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EquipmentUsage {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    equipmentId: ").append(toIndentedString(equipmentId)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    sourceLocation: ").append(toIndentedString(sourceLocation)).append("\n");
    sb.append("    usageStatus: ").append(toIndentedString(usageStatus)).append("\n");
    sb.append("    usedBy: ").append(toIndentedString(usedBy)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format("%screated_at%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `updated_at` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format("%supdated_at%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUpdatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `created_by` to the URL query string
    if (getCreatedBy() != null) {
      joiner.add(getCreatedBy().toUrlQueryString(prefix + "created_by" + suffix));
    }

    // add `updated_by` to the URL query string
    if (getUpdatedBy() != null) {
      joiner.add(getUpdatedBy().toUrlQueryString(prefix + "updated_by" + suffix));
    }

    // add `comment` to the URL query string
    if (getComment() != null) {
      joiner.add(String.format("%scomment%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getComment()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

