/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.demo.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * EquipmentBreakdownResponse
 */
@JsonPropertyOrder({
  EquipmentBreakdownResponse.JSON_PROPERTY_CATEGORY_DISTRIBUTION,
  EquipmentBreakdownResponse.JSON_PROPERTY_STATUS_BREAKDOWN,
  EquipmentBreakdownResponse.JSON_PROPERTY_USAGE_BY_JOB,
  EquipmentBreakdownResponse.JSON_PROPERTY_MAINTENANCE_COST_BY_EQUIPMENT,
  EquipmentBreakdownResponse.JSON_PROPERTY_LEASED_EQUIPMENT,
  EquipmentBreakdownResponse.JSON_PROPERTY_SCHEDULED_MAINTENANCES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-17T16:47:13.835321067+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class EquipmentBreakdownResponse {
  public static final String JSON_PROPERTY_CATEGORY_DISTRIBUTION = "category_distribution";
  private List<Object> categoryDistribution = new ArrayList<>();

  public static final String JSON_PROPERTY_STATUS_BREAKDOWN = "status_breakdown";
  private List<Object> statusBreakdown = new ArrayList<>();

  public static final String JSON_PROPERTY_USAGE_BY_JOB = "usage_by_job";
  private List<Object> usageByJob = new ArrayList<>();

  public static final String JSON_PROPERTY_MAINTENANCE_COST_BY_EQUIPMENT = "maintenance_cost_by_equipment";
  private List<Object> maintenanceCostByEquipment = new ArrayList<>();

  public static final String JSON_PROPERTY_LEASED_EQUIPMENT = "leased_equipment";
  private List<Object> leasedEquipment = new ArrayList<>();

  public static final String JSON_PROPERTY_SCHEDULED_MAINTENANCES = "scheduled_maintenances";
  private List<Object> scheduledMaintenances = new ArrayList<>();

  public EquipmentBreakdownResponse() { 
  }

  public EquipmentBreakdownResponse categoryDistribution(List<Object> categoryDistribution) {
    this.categoryDistribution = categoryDistribution;
    return this;
  }

  public EquipmentBreakdownResponse addCategoryDistributionItem(Object categoryDistributionItem) {
    if (this.categoryDistribution == null) {
      this.categoryDistribution = new ArrayList<>();
    }
    this.categoryDistribution.add(categoryDistributionItem);
    return this;
  }

   /**
   * Get categoryDistribution
   * @return categoryDistribution
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CATEGORY_DISTRIBUTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getCategoryDistribution() {
    return categoryDistribution;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY_DISTRIBUTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategoryDistribution(List<Object> categoryDistribution) {
    this.categoryDistribution = categoryDistribution;
  }


  public EquipmentBreakdownResponse statusBreakdown(List<Object> statusBreakdown) {
    this.statusBreakdown = statusBreakdown;
    return this;
  }

  public EquipmentBreakdownResponse addStatusBreakdownItem(Object statusBreakdownItem) {
    if (this.statusBreakdown == null) {
      this.statusBreakdown = new ArrayList<>();
    }
    this.statusBreakdown.add(statusBreakdownItem);
    return this;
  }

   /**
   * Get statusBreakdown
   * @return statusBreakdown
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS_BREAKDOWN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getStatusBreakdown() {
    return statusBreakdown;
  }


  @JsonProperty(JSON_PROPERTY_STATUS_BREAKDOWN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusBreakdown(List<Object> statusBreakdown) {
    this.statusBreakdown = statusBreakdown;
  }


  public EquipmentBreakdownResponse usageByJob(List<Object> usageByJob) {
    this.usageByJob = usageByJob;
    return this;
  }

  public EquipmentBreakdownResponse addUsageByJobItem(Object usageByJobItem) {
    if (this.usageByJob == null) {
      this.usageByJob = new ArrayList<>();
    }
    this.usageByJob.add(usageByJobItem);
    return this;
  }

   /**
   * Get usageByJob
   * @return usageByJob
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USAGE_BY_JOB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getUsageByJob() {
    return usageByJob;
  }


  @JsonProperty(JSON_PROPERTY_USAGE_BY_JOB)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsageByJob(List<Object> usageByJob) {
    this.usageByJob = usageByJob;
  }


  public EquipmentBreakdownResponse maintenanceCostByEquipment(List<Object> maintenanceCostByEquipment) {
    this.maintenanceCostByEquipment = maintenanceCostByEquipment;
    return this;
  }

  public EquipmentBreakdownResponse addMaintenanceCostByEquipmentItem(Object maintenanceCostByEquipmentItem) {
    if (this.maintenanceCostByEquipment == null) {
      this.maintenanceCostByEquipment = new ArrayList<>();
    }
    this.maintenanceCostByEquipment.add(maintenanceCostByEquipmentItem);
    return this;
  }

   /**
   * Get maintenanceCostByEquipment
   * @return maintenanceCostByEquipment
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAINTENANCE_COST_BY_EQUIPMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getMaintenanceCostByEquipment() {
    return maintenanceCostByEquipment;
  }


  @JsonProperty(JSON_PROPERTY_MAINTENANCE_COST_BY_EQUIPMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaintenanceCostByEquipment(List<Object> maintenanceCostByEquipment) {
    this.maintenanceCostByEquipment = maintenanceCostByEquipment;
  }


  public EquipmentBreakdownResponse leasedEquipment(List<Object> leasedEquipment) {
    this.leasedEquipment = leasedEquipment;
    return this;
  }

  public EquipmentBreakdownResponse addLeasedEquipmentItem(Object leasedEquipmentItem) {
    if (this.leasedEquipment == null) {
      this.leasedEquipment = new ArrayList<>();
    }
    this.leasedEquipment.add(leasedEquipmentItem);
    return this;
  }

   /**
   * Get leasedEquipment
   * @return leasedEquipment
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEASED_EQUIPMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getLeasedEquipment() {
    return leasedEquipment;
  }


  @JsonProperty(JSON_PROPERTY_LEASED_EQUIPMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeasedEquipment(List<Object> leasedEquipment) {
    this.leasedEquipment = leasedEquipment;
  }


  public EquipmentBreakdownResponse scheduledMaintenances(List<Object> scheduledMaintenances) {
    this.scheduledMaintenances = scheduledMaintenances;
    return this;
  }

  public EquipmentBreakdownResponse addScheduledMaintenancesItem(Object scheduledMaintenancesItem) {
    if (this.scheduledMaintenances == null) {
      this.scheduledMaintenances = new ArrayList<>();
    }
    this.scheduledMaintenances.add(scheduledMaintenancesItem);
    return this;
  }

   /**
   * Get scheduledMaintenances
   * @return scheduledMaintenances
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCHEDULED_MAINTENANCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getScheduledMaintenances() {
    return scheduledMaintenances;
  }


  @JsonProperty(JSON_PROPERTY_SCHEDULED_MAINTENANCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduledMaintenances(List<Object> scheduledMaintenances) {
    this.scheduledMaintenances = scheduledMaintenances;
  }


  /**
   * Return true if this EquipmentBreakdownResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EquipmentBreakdownResponse equipmentBreakdownResponse = (EquipmentBreakdownResponse) o;
    return Objects.equals(this.categoryDistribution, equipmentBreakdownResponse.categoryDistribution) &&
        Objects.equals(this.statusBreakdown, equipmentBreakdownResponse.statusBreakdown) &&
        Objects.equals(this.usageByJob, equipmentBreakdownResponse.usageByJob) &&
        Objects.equals(this.maintenanceCostByEquipment, equipmentBreakdownResponse.maintenanceCostByEquipment) &&
        Objects.equals(this.leasedEquipment, equipmentBreakdownResponse.leasedEquipment) &&
        Objects.equals(this.scheduledMaintenances, equipmentBreakdownResponse.scheduledMaintenances);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryDistribution, statusBreakdown, usageByJob, maintenanceCostByEquipment, leasedEquipment, scheduledMaintenances);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EquipmentBreakdownResponse {\n");
    sb.append("    categoryDistribution: ").append(toIndentedString(categoryDistribution)).append("\n");
    sb.append("    statusBreakdown: ").append(toIndentedString(statusBreakdown)).append("\n");
    sb.append("    usageByJob: ").append(toIndentedString(usageByJob)).append("\n");
    sb.append("    maintenanceCostByEquipment: ").append(toIndentedString(maintenanceCostByEquipment)).append("\n");
    sb.append("    leasedEquipment: ").append(toIndentedString(leasedEquipment)).append("\n");
    sb.append("    scheduledMaintenances: ").append(toIndentedString(scheduledMaintenances)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `category_distribution` to the URL query string
    if (getCategoryDistribution() != null) {
      for (int i = 0; i < getCategoryDistribution().size(); i++) {
        joiner.add(String.format("%scategory_distribution%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(String.valueOf(getCategoryDistribution().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `status_breakdown` to the URL query string
    if (getStatusBreakdown() != null) {
      for (int i = 0; i < getStatusBreakdown().size(); i++) {
        joiner.add(String.format("%sstatus_breakdown%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(String.valueOf(getStatusBreakdown().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `usage_by_job` to the URL query string
    if (getUsageByJob() != null) {
      for (int i = 0; i < getUsageByJob().size(); i++) {
        joiner.add(String.format("%susage_by_job%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(String.valueOf(getUsageByJob().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `maintenance_cost_by_equipment` to the URL query string
    if (getMaintenanceCostByEquipment() != null) {
      for (int i = 0; i < getMaintenanceCostByEquipment().size(); i++) {
        joiner.add(String.format("%smaintenance_cost_by_equipment%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(String.valueOf(getMaintenanceCostByEquipment().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `leased_equipment` to the URL query string
    if (getLeasedEquipment() != null) {
      for (int i = 0; i < getLeasedEquipment().size(); i++) {
        joiner.add(String.format("%sleased_equipment%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(String.valueOf(getLeasedEquipment().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    // add `scheduled_maintenances` to the URL query string
    if (getScheduledMaintenances() != null) {
      for (int i = 0; i < getScheduledMaintenances().size(); i++) {
        joiner.add(String.format("%sscheduled_maintenances%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(String.valueOf(getScheduledMaintenances().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    return joiner.toString();
  }
}

