/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.demo.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.demo.client.model.CrupdateUser;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * LeaveBalance
 */
@JsonPropertyOrder({
  LeaveBalance.JSON_PROPERTY_USER,
  LeaveBalance.JSON_PROPERTY_YEAR,
  LeaveBalance.JSON_PROPERTY_ACCRUED_DAYS,
  LeaveBalance.JSON_PROPERTY_TAKEN_DAYS,
  LeaveBalance.JSON_PROPERTY_REMAINING_DAYS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-16T16:39:05.632791630+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class LeaveBalance {
  public static final String JSON_PROPERTY_USER = "user";
  private CrupdateUser user;

  public static final String JSON_PROPERTY_YEAR = "year";
  private Integer year;

  public static final String JSON_PROPERTY_ACCRUED_DAYS = "accrued_days";
  private BigDecimal accruedDays;

  public static final String JSON_PROPERTY_TAKEN_DAYS = "taken_days";
  private BigDecimal takenDays;

  public static final String JSON_PROPERTY_REMAINING_DAYS = "remaining_days";
  private BigDecimal remainingDays;

  public LeaveBalance() { 
  }

  public LeaveBalance user(CrupdateUser user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CrupdateUser getUser() {
    return user;
  }


  @JsonProperty(JSON_PROPERTY_USER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUser(CrupdateUser user) {
    this.user = user;
  }


  public LeaveBalance year(Integer year) {
    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getYear() {
    return year;
  }


  @JsonProperty(JSON_PROPERTY_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setYear(Integer year) {
    this.year = year;
  }


  public LeaveBalance accruedDays(BigDecimal accruedDays) {
    this.accruedDays = accruedDays;
    return this;
  }

   /**
   * Get accruedDays
   * @return accruedDays
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCRUED_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getAccruedDays() {
    return accruedDays;
  }


  @JsonProperty(JSON_PROPERTY_ACCRUED_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccruedDays(BigDecimal accruedDays) {
    this.accruedDays = accruedDays;
  }


  public LeaveBalance takenDays(BigDecimal takenDays) {
    this.takenDays = takenDays;
    return this;
  }

   /**
   * Get takenDays
   * @return takenDays
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAKEN_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getTakenDays() {
    return takenDays;
  }


  @JsonProperty(JSON_PROPERTY_TAKEN_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTakenDays(BigDecimal takenDays) {
    this.takenDays = takenDays;
  }


  public LeaveBalance remainingDays(BigDecimal remainingDays) {
    this.remainingDays = remainingDays;
    return this;
  }

   /**
   * Get remainingDays
   * @return remainingDays
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REMAINING_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getRemainingDays() {
    return remainingDays;
  }


  @JsonProperty(JSON_PROPERTY_REMAINING_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRemainingDays(BigDecimal remainingDays) {
    this.remainingDays = remainingDays;
  }


  /**
   * Return true if this LeaveBalance object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LeaveBalance leaveBalance = (LeaveBalance) o;
    return Objects.equals(this.user, leaveBalance.user) &&
        Objects.equals(this.year, leaveBalance.year) &&
        Objects.equals(this.accruedDays, leaveBalance.accruedDays) &&
        Objects.equals(this.takenDays, leaveBalance.takenDays) &&
        Objects.equals(this.remainingDays, leaveBalance.remainingDays);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user, year, accruedDays, takenDays, remainingDays);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LeaveBalance {\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    accruedDays: ").append(toIndentedString(accruedDays)).append("\n");
    sb.append("    takenDays: ").append(toIndentedString(takenDays)).append("\n");
    sb.append("    remainingDays: ").append(toIndentedString(remainingDays)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `user` to the URL query string
    if (getUser() != null) {
      joiner.add(getUser().toUrlQueryString(prefix + "user" + suffix));
    }

    // add `year` to the URL query string
    if (getYear() != null) {
      joiner.add(String.format("%syear%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getYear()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `accrued_days` to the URL query string
    if (getAccruedDays() != null) {
      joiner.add(String.format("%saccrued_days%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAccruedDays()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `taken_days` to the URL query string
    if (getTakenDays() != null) {
      joiner.add(String.format("%staken_days%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTakenDays()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `remaining_days` to the URL query string
    if (getRemainingDays() != null) {
      joiner.add(String.format("%sremaining_days%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRemainingDays()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

