/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.demo.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.demo.client.model.AuditUser;
import com.example.demo.client.model.CrupdateLoan;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * LoanRepayment
 */
@JsonPropertyOrder({
  LoanRepayment.JSON_PROPERTY_ID,
  LoanRepayment.JSON_PROPERTY_PAYMENT_DATE,
  LoanRepayment.JSON_PROPERTY_AMOUNT,
  LoanRepayment.JSON_PROPERTY_PRINCIPAL_PORTION,
  LoanRepayment.JSON_PROPERTY_INTEREST_PORTION,
  LoanRepayment.JSON_PROPERTY_LOAN,
  LoanRepayment.JSON_PROPERTY_CREATED_AT,
  LoanRepayment.JSON_PROPERTY_UPDATED_AT,
  LoanRepayment.JSON_PROPERTY_CREATED_BY,
  LoanRepayment.JSON_PROPERTY_UPDATED_BY,
  LoanRepayment.JSON_PROPERTY_COMMENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-09T23:21:50.737140530+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class LoanRepayment {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_PAYMENT_DATE = "payment_date";
  private java.time.LocalDate paymentDate;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private Integer amount;

  public static final String JSON_PROPERTY_PRINCIPAL_PORTION = "principal_portion";
  private Integer principalPortion;

  public static final String JSON_PROPERTY_INTEREST_PORTION = "interest_portion";
  private Integer interestPortion;

  public static final String JSON_PROPERTY_LOAN = "loan";
  private CrupdateLoan loan;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private java.time.Instant createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private java.time.Instant updatedAt;

  public static final String JSON_PROPERTY_CREATED_BY = "created_by";
  private AuditUser createdBy;

  public static final String JSON_PROPERTY_UPDATED_BY = "updated_by";
  private AuditUser updatedBy;

  public static final String JSON_PROPERTY_COMMENT = "comment";
  private String comment;

  public LoanRepayment() { 
  }

  public LoanRepayment id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public LoanRepayment paymentDate(java.time.LocalDate paymentDate) {
    this.paymentDate = paymentDate;
    return this;
  }

   /**
   * Get paymentDate
   * @return paymentDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.LocalDate getPaymentDate() {
    return paymentDate;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentDate(java.time.LocalDate paymentDate) {
    this.paymentDate = paymentDate;
  }


  public LoanRepayment amount(Integer amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Total repayment amount
   * @return amount
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmount(Integer amount) {
    this.amount = amount;
  }


  public LoanRepayment principalPortion(Integer principalPortion) {
    this.principalPortion = principalPortion;
    return this;
  }

   /**
   * Portion of the payment that goes to principal (auto-calculated)
   * @return principalPortion
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRINCIPAL_PORTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPrincipalPortion() {
    return principalPortion;
  }


  @JsonProperty(JSON_PROPERTY_PRINCIPAL_PORTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrincipalPortion(Integer principalPortion) {
    this.principalPortion = principalPortion;
  }


  public LoanRepayment interestPortion(Integer interestPortion) {
    this.interestPortion = interestPortion;
    return this;
  }

   /**
   * Portion of the payment that goes to interest (auto-calculated)
   * @return interestPortion
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTEREST_PORTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getInterestPortion() {
    return interestPortion;
  }


  @JsonProperty(JSON_PROPERTY_INTEREST_PORTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterestPortion(Integer interestPortion) {
    this.interestPortion = interestPortion;
  }


  public LoanRepayment loan(CrupdateLoan loan) {
    this.loan = loan;
    return this;
  }

   /**
   * Loan this repayment is related to
   * @return loan
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CrupdateLoan getLoan() {
    return loan;
  }


  @JsonProperty(JSON_PROPERTY_LOAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLoan(CrupdateLoan loan) {
    this.loan = loan;
  }


  public LoanRepayment createdAt(java.time.Instant createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(java.time.Instant createdAt) {
    this.createdAt = createdAt;
  }


  public LoanRepayment updatedAt(java.time.Instant updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.Instant getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(java.time.Instant updatedAt) {
    this.updatedAt = updatedAt;
  }


  public LoanRepayment createdBy(AuditUser createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditUser getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedBy(AuditUser createdBy) {
    this.createdBy = createdBy;
  }


  public LoanRepayment updatedBy(AuditUser updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * Get updatedBy
   * @return updatedBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditUser getUpdatedBy() {
    return updatedBy;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedBy(AuditUser updatedBy) {
    this.updatedBy = updatedBy;
  }


  public LoanRepayment comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComment() {
    return comment;
  }


  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComment(String comment) {
    this.comment = comment;
  }


  /**
   * Return true if this LoanRepayment object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoanRepayment loanRepayment = (LoanRepayment) o;
    return Objects.equals(this.id, loanRepayment.id) &&
        Objects.equals(this.paymentDate, loanRepayment.paymentDate) &&
        Objects.equals(this.amount, loanRepayment.amount) &&
        Objects.equals(this.principalPortion, loanRepayment.principalPortion) &&
        Objects.equals(this.interestPortion, loanRepayment.interestPortion) &&
        Objects.equals(this.loan, loanRepayment.loan) &&
        Objects.equals(this.createdAt, loanRepayment.createdAt) &&
        Objects.equals(this.updatedAt, loanRepayment.updatedAt) &&
        Objects.equals(this.createdBy, loanRepayment.createdBy) &&
        Objects.equals(this.updatedBy, loanRepayment.updatedBy) &&
        Objects.equals(this.comment, loanRepayment.comment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, paymentDate, amount, principalPortion, interestPortion, loan, createdAt, updatedAt, createdBy, updatedBy, comment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoanRepayment {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    paymentDate: ").append(toIndentedString(paymentDate)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    principalPortion: ").append(toIndentedString(principalPortion)).append("\n");
    sb.append("    interestPortion: ").append(toIndentedString(interestPortion)).append("\n");
    sb.append("    loan: ").append(toIndentedString(loan)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format("%screated_at%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `updated_at` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format("%supdated_at%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUpdatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `created_by` to the URL query string
    if (getCreatedBy() != null) {
      joiner.add(getCreatedBy().toUrlQueryString(prefix + "created_by" + suffix));
    }

    // add `updated_by` to the URL query string
    if (getUpdatedBy() != null) {
      joiner.add(getUpdatedBy().toUrlQueryString(prefix + "updated_by" + suffix));
    }

    // add `comment` to the URL query string
    if (getComment() != null) {
      joiner.add(String.format("%scomment%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getComment()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

