/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.demo.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.demo.client.model.AuditUser;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.Date;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * MaterialConsumption
 */
@JsonPropertyOrder({
  MaterialConsumption.JSON_PROPERTY_ID,
  MaterialConsumption.JSON_PROPERTY_MATERIAL_ID,
  MaterialConsumption.JSON_PROPERTY_WAREHOUSE_ID,
  MaterialConsumption.JSON_PROPERTY_QUANTITY,
  MaterialConsumption.JSON_PROPERTY_CONSUMPTION_DATE,
  MaterialConsumption.JSON_PROPERTY_JOB_ID,
  MaterialConsumption.JSON_PROPERTY_REASON,
  MaterialConsumption.JSON_PROPERTY_CONSUMPTION_STATUS,
  MaterialConsumption.JSON_PROPERTY_CREATED_AT,
  MaterialConsumption.JSON_PROPERTY_UPDATED_AT,
  MaterialConsumption.JSON_PROPERTY_CREATED_BY,
  MaterialConsumption.JSON_PROPERTY_UPDATED_BY,
  MaterialConsumption.JSON_PROPERTY_COMMENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-30T17:19:15.606578257+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class MaterialConsumption {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_MATERIAL_ID = "material_id";
  private String materialId;

  public static final String JSON_PROPERTY_WAREHOUSE_ID = "warehouse_id";
  private String warehouseId;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private Integer quantity;

  public static final String JSON_PROPERTY_CONSUMPTION_DATE = "consumption_date";
  private java.time.LocalDate consumptionDate;

  public static final String JSON_PROPERTY_JOB_ID = "job_id";
  private String jobId;

  public static final String JSON_PROPERTY_REASON = "reason";
  private String reason;

  public static final String JSON_PROPERTY_CONSUMPTION_STATUS = "consumption_status";
  private String consumptionStatus;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  private java.time.Instant createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  private java.time.Instant updatedAt;

  public static final String JSON_PROPERTY_CREATED_BY = "created_by";
  private AuditUser createdBy;

  public static final String JSON_PROPERTY_UPDATED_BY = "updated_by";
  private AuditUser updatedBy;

  public static final String JSON_PROPERTY_COMMENT = "comment";
  private String comment;

  public MaterialConsumption() { 
  }

  public MaterialConsumption id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public MaterialConsumption materialId(String materialId) {
    this.materialId = materialId;
    return this;
  }

   /**
   * Get materialId
   * @return materialId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATERIAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMaterialId() {
    return materialId;
  }


  @JsonProperty(JSON_PROPERTY_MATERIAL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaterialId(String materialId) {
    this.materialId = materialId;
  }


  public MaterialConsumption warehouseId(String warehouseId) {
    this.warehouseId = warehouseId;
    return this;
  }

   /**
   * Get warehouseId
   * @return warehouseId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WAREHOUSE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWarehouseId() {
    return warehouseId;
  }


  @JsonProperty(JSON_PROPERTY_WAREHOUSE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWarehouseId(String warehouseId) {
    this.warehouseId = warehouseId;
  }


  public MaterialConsumption quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  public MaterialConsumption consumptionDate(java.time.LocalDate consumptionDate) {
    this.consumptionDate = consumptionDate;
    return this;
  }

   /**
   * Get consumptionDate
   * @return consumptionDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONSUMPTION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.LocalDate getConsumptionDate() {
    return consumptionDate;
  }


  @JsonProperty(JSON_PROPERTY_CONSUMPTION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConsumptionDate(java.time.LocalDate consumptionDate) {
    this.consumptionDate = consumptionDate;
  }


  public MaterialConsumption jobId(String jobId) {
    this.jobId = jobId;
    return this;
  }

   /**
   * Get jobId
   * @return jobId
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getJobId() {
    return jobId;
  }


  @JsonProperty(JSON_PROPERTY_JOB_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJobId(String jobId) {
    this.jobId = jobId;
  }


  public MaterialConsumption reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Get reason
   * @return reason
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(String reason) {
    this.reason = reason;
  }


  public MaterialConsumption consumptionStatus(String consumptionStatus) {
    this.consumptionStatus = consumptionStatus;
    return this;
  }

   /**
   * Get consumptionStatus
   * @return consumptionStatus
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONSUMPTION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getConsumptionStatus() {
    return consumptionStatus;
  }


  @JsonProperty(JSON_PROPERTY_CONSUMPTION_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setConsumptionStatus(String consumptionStatus) {
    this.consumptionStatus = consumptionStatus;
  }


  public MaterialConsumption createdAt(java.time.Instant createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(java.time.Instant createdAt) {
    this.createdAt = createdAt;
  }


  public MaterialConsumption updatedAt(java.time.Instant updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.time.Instant getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(java.time.Instant updatedAt) {
    this.updatedAt = updatedAt;
  }


  public MaterialConsumption createdBy(AuditUser createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditUser getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedBy(AuditUser createdBy) {
    this.createdBy = createdBy;
  }


  public MaterialConsumption updatedBy(AuditUser updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

   /**
   * Get updatedBy
   * @return updatedBy
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AuditUser getUpdatedBy() {
    return updatedBy;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedBy(AuditUser updatedBy) {
    this.updatedBy = updatedBy;
  }


  public MaterialConsumption comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComment() {
    return comment;
  }


  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComment(String comment) {
    this.comment = comment;
  }


  /**
   * Return true if this MaterialConsumption object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MaterialConsumption materialConsumption = (MaterialConsumption) o;
    return Objects.equals(this.id, materialConsumption.id) &&
        Objects.equals(this.materialId, materialConsumption.materialId) &&
        Objects.equals(this.warehouseId, materialConsumption.warehouseId) &&
        Objects.equals(this.quantity, materialConsumption.quantity) &&
        Objects.equals(this.consumptionDate, materialConsumption.consumptionDate) &&
        Objects.equals(this.jobId, materialConsumption.jobId) &&
        Objects.equals(this.reason, materialConsumption.reason) &&
        Objects.equals(this.consumptionStatus, materialConsumption.consumptionStatus) &&
        Objects.equals(this.createdAt, materialConsumption.createdAt) &&
        Objects.equals(this.updatedAt, materialConsumption.updatedAt) &&
        Objects.equals(this.createdBy, materialConsumption.createdBy) &&
        Objects.equals(this.updatedBy, materialConsumption.updatedBy) &&
        Objects.equals(this.comment, materialConsumption.comment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, materialId, warehouseId, quantity, consumptionDate, jobId, reason, consumptionStatus, createdAt, updatedAt, createdBy, updatedBy, comment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaterialConsumption {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    materialId: ").append(toIndentedString(materialId)).append("\n");
    sb.append("    warehouseId: ").append(toIndentedString(warehouseId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    consumptionDate: ").append(toIndentedString(consumptionDate)).append("\n");
    sb.append("    jobId: ").append(toIndentedString(jobId)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    consumptionStatus: ").append(toIndentedString(consumptionStatus)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format("%screated_at%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `updated_at` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format("%supdated_at%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUpdatedAt()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `created_by` to the URL query string
    if (getCreatedBy() != null) {
      joiner.add(getCreatedBy().toUrlQueryString(prefix + "created_by" + suffix));
    }

    // add `updated_by` to the URL query string
    if (getUpdatedBy() != null) {
      joiner.add(getUpdatedBy().toUrlQueryString(prefix + "updated_by" + suffix));
    }

    // add `comment` to the URL query string
    if (getComment() != null) {
      joiner.add(String.format("%scomment%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getComment()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

