/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.demo.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.demo.client.model.TravelOperationEquipmentLine;
import com.example.demo.client.model.TravelOperationMaterialLine;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * TravelOperationContainerLine
 */
@JsonPropertyOrder({
  TravelOperationContainerLine.JSON_PROPERTY_ID,
  TravelOperationContainerLine.JSON_PROPERTY_NAME,
  TravelOperationContainerLine.JSON_PROPERTY_DESCRIPTION,
  TravelOperationContainerLine.JSON_PROPERTY_EQUIPMENT_LINES,
  TravelOperationContainerLine.JSON_PROPERTY_MATERIAL_LINES,
  TravelOperationContainerLine.JSON_PROPERTY_COMMENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-23T02:32:35.190314305+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class TravelOperationContainerLine {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_EQUIPMENT_LINES = "equipment_lines";
  private List<TravelOperationEquipmentLine> equipmentLines = new ArrayList<>();

  public static final String JSON_PROPERTY_MATERIAL_LINES = "material_lines";
  private List<TravelOperationMaterialLine> materialLines = new ArrayList<>();

  public static final String JSON_PROPERTY_COMMENT = "comment";
  private String comment;

  public TravelOperationContainerLine() { 
  }

  public TravelOperationContainerLine id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public TravelOperationContainerLine name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public TravelOperationContainerLine description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public TravelOperationContainerLine equipmentLines(List<TravelOperationEquipmentLine> equipmentLines) {
    this.equipmentLines = equipmentLines;
    return this;
  }

  public TravelOperationContainerLine addEquipmentLinesItem(TravelOperationEquipmentLine equipmentLinesItem) {
    if (this.equipmentLines == null) {
      this.equipmentLines = new ArrayList<>();
    }
    this.equipmentLines.add(equipmentLinesItem);
    return this;
  }

   /**
   * Get equipmentLines
   * @return equipmentLines
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EQUIPMENT_LINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TravelOperationEquipmentLine> getEquipmentLines() {
    return equipmentLines;
  }


  @JsonProperty(JSON_PROPERTY_EQUIPMENT_LINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEquipmentLines(List<TravelOperationEquipmentLine> equipmentLines) {
    this.equipmentLines = equipmentLines;
  }


  public TravelOperationContainerLine materialLines(List<TravelOperationMaterialLine> materialLines) {
    this.materialLines = materialLines;
    return this;
  }

  public TravelOperationContainerLine addMaterialLinesItem(TravelOperationMaterialLine materialLinesItem) {
    if (this.materialLines == null) {
      this.materialLines = new ArrayList<>();
    }
    this.materialLines.add(materialLinesItem);
    return this;
  }

   /**
   * Get materialLines
   * @return materialLines
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATERIAL_LINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TravelOperationMaterialLine> getMaterialLines() {
    return materialLines;
  }


  @JsonProperty(JSON_PROPERTY_MATERIAL_LINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaterialLines(List<TravelOperationMaterialLine> materialLines) {
    this.materialLines = materialLines;
  }


  public TravelOperationContainerLine comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getComment() {
    return comment;
  }


  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComment(String comment) {
    this.comment = comment;
  }


  /**
   * Return true if this TravelOperationContainerLine object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TravelOperationContainerLine travelOperationContainerLine = (TravelOperationContainerLine) o;
    return Objects.equals(this.id, travelOperationContainerLine.id) &&
        Objects.equals(this.name, travelOperationContainerLine.name) &&
        Objects.equals(this.description, travelOperationContainerLine.description) &&
        Objects.equals(this.equipmentLines, travelOperationContainerLine.equipmentLines) &&
        Objects.equals(this.materialLines, travelOperationContainerLine.materialLines) &&
        Objects.equals(this.comment, travelOperationContainerLine.comment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, equipmentLines, materialLines, comment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TravelOperationContainerLine {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    equipmentLines: ").append(toIndentedString(equipmentLines)).append("\n");
    sb.append("    materialLines: ").append(toIndentedString(materialLines)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `comment` to the URL query string
    if (getComment() != null) {
      joiner.add(String.format("%scomment%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getComment()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

