/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.example.demo.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.example.demo.client.model.JobWithFinancials;
import com.example.demo.client.model.YearlyReportSummary;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * YearlyReport
 */
@JsonPropertyOrder({
  YearlyReport.JSON_PROPERTY_YEAR,
  YearlyReport.JSON_PROPERTY_JOBS_WITH_FINANCIALS,
  YearlyReport.JSON_PROPERTY_SUMMARY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-09T23:21:50.737140530+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class YearlyReport {
  public static final String JSON_PROPERTY_YEAR = "year";
  private Integer year;

  public static final String JSON_PROPERTY_JOBS_WITH_FINANCIALS = "jobs_with_financials";
  private List<JobWithFinancials> jobsWithFinancials = new ArrayList<>();

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  private YearlyReportSummary summary;

  public YearlyReport() { 
  }

  public YearlyReport year(Integer year) {
    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getYear() {
    return year;
  }


  @JsonProperty(JSON_PROPERTY_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setYear(Integer year) {
    this.year = year;
  }


  public YearlyReport jobsWithFinancials(List<JobWithFinancials> jobsWithFinancials) {
    this.jobsWithFinancials = jobsWithFinancials;
    return this;
  }

  public YearlyReport addJobsWithFinancialsItem(JobWithFinancials jobsWithFinancialsItem) {
    if (this.jobsWithFinancials == null) {
      this.jobsWithFinancials = new ArrayList<>();
    }
    this.jobsWithFinancials.add(jobsWithFinancialsItem);
    return this;
  }

   /**
   * Get jobsWithFinancials
   * @return jobsWithFinancials
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_JOBS_WITH_FINANCIALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<JobWithFinancials> getJobsWithFinancials() {
    return jobsWithFinancials;
  }


  @JsonProperty(JSON_PROPERTY_JOBS_WITH_FINANCIALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJobsWithFinancials(List<JobWithFinancials> jobsWithFinancials) {
    this.jobsWithFinancials = jobsWithFinancials;
  }


  public YearlyReport summary(YearlyReportSummary summary) {
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public YearlyReportSummary getSummary() {
    return summary;
  }


  @JsonProperty(JSON_PROPERTY_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSummary(YearlyReportSummary summary) {
    this.summary = summary;
  }


  /**
   * Return true if this YearlyReport object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    YearlyReport yearlyReport = (YearlyReport) o;
    return Objects.equals(this.year, yearlyReport.year) &&
        Objects.equals(this.jobsWithFinancials, yearlyReport.jobsWithFinancials) &&
        Objects.equals(this.summary, yearlyReport.summary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(year, jobsWithFinancials, summary);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class YearlyReport {\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    jobsWithFinancials: ").append(toIndentedString(jobsWithFinancials)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `year` to the URL query string
    if (getYear() != null) {
      joiner.add(String.format("%syear%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getYear()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `jobs_with_financials` to the URL query string
    if (getJobsWithFinancials() != null) {
      for (int i = 0; i < getJobsWithFinancials().size(); i++) {
        if (getJobsWithFinancials().get(i) != null) {
          joiner.add(getJobsWithFinancials().get(i).toUrlQueryString(String.format("%sjobs_with_financials%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `summary` to the URL query string
    if (getSummary() != null) {
      joiner.add(getSummary().toUrlQueryString(prefix + "summary" + suffix));
    }

    return joiner.toString();
  }
}

