/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.demo.client.api;

import com.example.demo.client.invoker.ApiClient;
import com.example.demo.client.invoker.ApiException;
import com.example.demo.client.invoker.ApiResponse;
import com.example.demo.client.invoker.Pair;

import com.example.demo.client.model.BadRequestException;
import com.example.demo.client.model.CashAccount;
import com.example.demo.client.model.CrupdateCashAccount;
import com.example.demo.client.model.InternalServerException;
import com.example.demo.client.model.NotAuthorizedException;
import com.example.demo.client.model.ResourceNotFoundException;
import com.example.demo.client.model.TooManyRequestsException;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-01T18:19:40.950295941+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class CashAccountApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public CashAccountApi() {
    this(new ApiClient());
  }

  public CashAccountApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Create new cash accounts or update existing ones
   * 
   * @param compId  (required)
   * @param crupdateCashAccount  (required)
   * @return List&lt;CashAccount&gt;
   * @throws ApiException if fails to make API call
   */
  public List<CashAccount> crupdateCashAccounts(String compId, List<CrupdateCashAccount> crupdateCashAccount) throws ApiException {
    ApiResponse<List<CashAccount>> localVarResponse = crupdateCashAccountsWithHttpInfo(compId, crupdateCashAccount);
    return localVarResponse.getData();
  }

  /**
   * Create new cash accounts or update existing ones
   * 
   * @param compId  (required)
   * @param crupdateCashAccount  (required)
   * @return ApiResponse&lt;List&lt;CashAccount&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<CashAccount>> crupdateCashAccountsWithHttpInfo(String compId, List<CrupdateCashAccount> crupdateCashAccount) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = crupdateCashAccountsRequestBuilder(compId, crupdateCashAccount);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("crupdateCashAccounts", localVarResponse);
        }
        return new ApiResponse<List<CashAccount>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<CashAccount>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder crupdateCashAccountsRequestBuilder(String compId, List<CrupdateCashAccount> crupdateCashAccount) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling crupdateCashAccounts");
    }
    // verify the required parameter 'crupdateCashAccount' is set
    if (crupdateCashAccount == null) {
      throw new ApiException(400, "Missing the required parameter 'crupdateCashAccount' when calling crupdateCashAccounts");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/cash_accounts"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(crupdateCashAccount);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete a cash account by identifier
   * 
   * @param compId  (required)
   * @param id  (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteCashAccountById(String compId, String id) throws ApiException {
    deleteCashAccountByIdWithHttpInfo(compId, id);
  }

  /**
   * Delete a cash account by identifier
   * 
   * @param compId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteCashAccountByIdWithHttpInfo(String compId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteCashAccountByIdRequestBuilder(compId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteCashAccountById", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteCashAccountByIdRequestBuilder(String compId, String id) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling deleteCashAccountById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteCashAccountById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/cash_accounts/{id}"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get a cash account by identifier
   * 
   * @param compId  (required)
   * @param id  (required)
   * @return CashAccount
   * @throws ApiException if fails to make API call
   */
  public CashAccount getCashAccountById(String compId, String id) throws ApiException {
    ApiResponse<CashAccount> localVarResponse = getCashAccountByIdWithHttpInfo(compId, id);
    return localVarResponse.getData();
  }

  /**
   * Get a cash account by identifier
   * 
   * @param compId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;CashAccount&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CashAccount> getCashAccountByIdWithHttpInfo(String compId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getCashAccountByIdRequestBuilder(compId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getCashAccountById", localVarResponse);
        }
        return new ApiResponse<CashAccount>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<CashAccount>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getCashAccountByIdRequestBuilder(String compId, String id) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling getCashAccountById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getCashAccountById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/cash_accounts/{id}"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all cash accounts
   * 
   * @param compId  (required)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @return List&lt;CashAccount&gt;
   * @throws ApiException if fails to make API call
   */
  public List<CashAccount> getCashAccounts(String compId, Integer page, Integer pageSize) throws ApiException {
    ApiResponse<List<CashAccount>> localVarResponse = getCashAccountsWithHttpInfo(compId, page, pageSize);
    return localVarResponse.getData();
  }

  /**
   * Get all cash accounts
   * 
   * @param compId  (required)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @return ApiResponse&lt;List&lt;CashAccount&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<CashAccount>> getCashAccountsWithHttpInfo(String compId, Integer page, Integer pageSize) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getCashAccountsRequestBuilder(compId, page, pageSize);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getCashAccounts", localVarResponse);
        }
        return new ApiResponse<List<CashAccount>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<CashAccount>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getCashAccountsRequestBuilder(String compId, Integer page, Integer pageSize) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling getCashAccounts");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/cash_accounts"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "page_size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page_size", pageSize));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
