/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.demo.client.api;

import com.example.demo.client.invoker.ApiClient;
import com.example.demo.client.invoker.ApiException;
import com.example.demo.client.invoker.ApiResponse;
import com.example.demo.client.invoker.Pair;

import com.example.demo.client.model.BadRequestException;
import com.example.demo.client.model.CrupdateEquipmentUsage;
import com.example.demo.client.model.EquipmentUsage;
import com.example.demo.client.model.InternalServerException;
import com.example.demo.client.model.NotAuthorizedException;
import com.example.demo.client.model.ResourceNotFoundException;
import com.example.demo.client.model.TooManyRequestsException;
import com.example.demo.client.model.UsageStatus;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-01T18:19:40.950295941+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class EquipmentUsageApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public EquipmentUsageApi() {
    this(new ApiClient());
  }

  public EquipmentUsageApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Create new equipment usage records or update existing ones
   * 
   * @param compId  (required)
   * @param crupdateEquipmentUsage  (required)
   * @return List&lt;EquipmentUsage&gt;
   * @throws ApiException if fails to make API call
   */
  public List<EquipmentUsage> crupdateEquipmentUsages(String compId, List<CrupdateEquipmentUsage> crupdateEquipmentUsage) throws ApiException {
    ApiResponse<List<EquipmentUsage>> localVarResponse = crupdateEquipmentUsagesWithHttpInfo(compId, crupdateEquipmentUsage);
    return localVarResponse.getData();
  }

  /**
   * Create new equipment usage records or update existing ones
   * 
   * @param compId  (required)
   * @param crupdateEquipmentUsage  (required)
   * @return ApiResponse&lt;List&lt;EquipmentUsage&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<EquipmentUsage>> crupdateEquipmentUsagesWithHttpInfo(String compId, List<CrupdateEquipmentUsage> crupdateEquipmentUsage) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = crupdateEquipmentUsagesRequestBuilder(compId, crupdateEquipmentUsage);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("crupdateEquipmentUsages", localVarResponse);
        }
        return new ApiResponse<List<EquipmentUsage>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<EquipmentUsage>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder crupdateEquipmentUsagesRequestBuilder(String compId, List<CrupdateEquipmentUsage> crupdateEquipmentUsage) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling crupdateEquipmentUsages");
    }
    // verify the required parameter 'crupdateEquipmentUsage' is set
    if (crupdateEquipmentUsage == null) {
      throw new ApiException(400, "Missing the required parameter 'crupdateEquipmentUsage' when calling crupdateEquipmentUsages");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/equipment_usage"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(crupdateEquipmentUsage);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete an equipment usage record by identifier
   * 
   * @param compId  (required)
   * @param id  (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteEquipmentUsageById(String compId, String id) throws ApiException {
    deleteEquipmentUsageByIdWithHttpInfo(compId, id);
  }

  /**
   * Delete an equipment usage record by identifier
   * 
   * @param compId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteEquipmentUsageByIdWithHttpInfo(String compId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteEquipmentUsageByIdRequestBuilder(compId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteEquipmentUsageById", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteEquipmentUsageByIdRequestBuilder(String compId, String id) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling deleteEquipmentUsageById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteEquipmentUsageById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/equipment_usage/{id}"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get an equipment usage record by identifier
   * 
   * @param compId  (required)
   * @param id  (required)
   * @return EquipmentUsage
   * @throws ApiException if fails to make API call
   */
  public EquipmentUsage getEquipmentUsageById(String compId, String id) throws ApiException {
    ApiResponse<EquipmentUsage> localVarResponse = getEquipmentUsageByIdWithHttpInfo(compId, id);
    return localVarResponse.getData();
  }

  /**
   * Get an equipment usage record by identifier
   * 
   * @param compId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;EquipmentUsage&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EquipmentUsage> getEquipmentUsageByIdWithHttpInfo(String compId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEquipmentUsageByIdRequestBuilder(compId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEquipmentUsageById", localVarResponse);
        }
        return new ApiResponse<EquipmentUsage>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<EquipmentUsage>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEquipmentUsageByIdRequestBuilder(String compId, String id) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling getEquipmentUsageById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getEquipmentUsageById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/equipment_usage/{id}"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all equipment usage records
   * 
   * @param compId  (required)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @param jobId  (optional)
   * @return List&lt;EquipmentUsage&gt;
   * @throws ApiException if fails to make API call
   */
  public List<EquipmentUsage> getEquipmentUsages(String compId, Integer page, Integer pageSize, String jobId) throws ApiException {
    ApiResponse<List<EquipmentUsage>> localVarResponse = getEquipmentUsagesWithHttpInfo(compId, page, pageSize, jobId);
    return localVarResponse.getData();
  }

  /**
   * Get all equipment usage records
   * 
   * @param compId  (required)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @param jobId  (optional)
   * @return ApiResponse&lt;List&lt;EquipmentUsage&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<EquipmentUsage>> getEquipmentUsagesWithHttpInfo(String compId, Integer page, Integer pageSize, String jobId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getEquipmentUsagesRequestBuilder(compId, page, pageSize, jobId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getEquipmentUsages", localVarResponse);
        }
        return new ApiResponse<List<EquipmentUsage>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<EquipmentUsage>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getEquipmentUsagesRequestBuilder(String compId, Integer page, Integer pageSize, String jobId) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling getEquipmentUsages");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/equipment_usage"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "page_size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page_size", pageSize));
    localVarQueryParameterBaseName = "job_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("job_id", jobId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Return equipment from usage
   * 
   * @param compId  (required)
   * @param id  (required)
   * @param status  (required)
   * @return EquipmentUsage
   * @throws ApiException if fails to make API call
   */
  public EquipmentUsage returnEquipment(String compId, String id, UsageStatus status) throws ApiException {
    ApiResponse<EquipmentUsage> localVarResponse = returnEquipmentWithHttpInfo(compId, id, status);
    return localVarResponse.getData();
  }

  /**
   * Return equipment from usage
   * 
   * @param compId  (required)
   * @param id  (required)
   * @param status  (required)
   * @return ApiResponse&lt;EquipmentUsage&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EquipmentUsage> returnEquipmentWithHttpInfo(String compId, String id, UsageStatus status) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = returnEquipmentRequestBuilder(compId, id, status);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("returnEquipment", localVarResponse);
        }
        return new ApiResponse<EquipmentUsage>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<EquipmentUsage>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder returnEquipmentRequestBuilder(String compId, String id, UsageStatus status) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling returnEquipment");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling returnEquipment");
    }
    // verify the required parameter 'status' is set
    if (status == null) {
      throw new ApiException(400, "Missing the required parameter 'status' when calling returnEquipment");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/equipment_usage/{id}/return"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "status";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("status", status));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
