/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.demo.client.api;

import com.example.demo.client.invoker.ApiClient;
import com.example.demo.client.invoker.ApiException;
import com.example.demo.client.invoker.ApiResponse;
import com.example.demo.client.invoker.Pair;

import com.example.demo.client.model.BadRequestException;
import com.example.demo.client.model.CrupdateIncomeReceipt;
import com.example.demo.client.model.IncomeReceipt;
import com.example.demo.client.model.InternalServerException;
import com.example.demo.client.model.NotAuthorizedException;
import com.example.demo.client.model.PaginatedResponse;
import com.example.demo.client.model.ResourceNotFoundException;
import com.example.demo.client.model.TooManyRequestsException;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-16T12:45:29.977991642+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class IncomeReceiptApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public IncomeReceiptApi() {
    this(new ApiClient());
  }

  public IncomeReceiptApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Create new income receipts or update existing ones
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param crupdateIncomeReceipt  (required)
   * @param incomeId  (optional)
   * @return List&lt;IncomeReceipt&gt;
   * @throws ApiException if fails to make API call
   */
  public List<IncomeReceipt> crupdateIncomeReceipts(String userId, String companyId, String jobId, List<CrupdateIncomeReceipt> crupdateIncomeReceipt, String incomeId) throws ApiException {
    ApiResponse<List<IncomeReceipt>> localVarResponse = crupdateIncomeReceiptsWithHttpInfo(userId, companyId, jobId, crupdateIncomeReceipt, incomeId);
    return localVarResponse.getData();
  }

  /**
   * Create new income receipts or update existing ones
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param crupdateIncomeReceipt  (required)
   * @param incomeId  (optional)
   * @return ApiResponse&lt;List&lt;IncomeReceipt&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<IncomeReceipt>> crupdateIncomeReceiptsWithHttpInfo(String userId, String companyId, String jobId, List<CrupdateIncomeReceipt> crupdateIncomeReceipt, String incomeId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = crupdateIncomeReceiptsRequestBuilder(userId, companyId, jobId, crupdateIncomeReceipt, incomeId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("crupdateIncomeReceipts", localVarResponse);
        }
        return new ApiResponse<List<IncomeReceipt>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<IncomeReceipt>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder crupdateIncomeReceiptsRequestBuilder(String userId, String companyId, String jobId, List<CrupdateIncomeReceipt> crupdateIncomeReceipt, String incomeId) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling crupdateIncomeReceipts");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling crupdateIncomeReceipts");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling crupdateIncomeReceipts");
    }
    // verify the required parameter 'crupdateIncomeReceipt' is set
    if (crupdateIncomeReceipt == null) {
      throw new ApiException(400, "Missing the required parameter 'crupdateIncomeReceipt' when calling crupdateIncomeReceipts");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/jobs/{jobId}/incomes_receipts"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{jobId}", ApiClient.urlEncode(jobId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "income_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("income_id", incomeId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(crupdateIncomeReceipt);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete income receipt by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param id  (required)
   * @param incomeId  (optional)
   * @throws ApiException if fails to make API call
   */
  public void deleteIncomeReceiptById(String userId, String companyId, String jobId, String id, String incomeId) throws ApiException {
    deleteIncomeReceiptByIdWithHttpInfo(userId, companyId, jobId, id, incomeId);
  }

  /**
   * Delete income receipt by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param id  (required)
   * @param incomeId  (optional)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteIncomeReceiptByIdWithHttpInfo(String userId, String companyId, String jobId, String id, String incomeId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteIncomeReceiptByIdRequestBuilder(userId, companyId, jobId, id, incomeId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteIncomeReceiptById", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteIncomeReceiptByIdRequestBuilder(String userId, String companyId, String jobId, String id, String incomeId) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling deleteIncomeReceiptById");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling deleteIncomeReceiptById");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling deleteIncomeReceiptById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteIncomeReceiptById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/jobs/{jobId}/incomes_receipts/{id}"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{jobId}", ApiClient.urlEncode(jobId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "income_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("income_id", incomeId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get income receipt by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param id  (required)
   * @param incomeId  (optional)
   * @return IncomeReceipt
   * @throws ApiException if fails to make API call
   */
  public IncomeReceipt getIncomeReceiptById(String userId, String companyId, String jobId, String id, String incomeId) throws ApiException {
    ApiResponse<IncomeReceipt> localVarResponse = getIncomeReceiptByIdWithHttpInfo(userId, companyId, jobId, id, incomeId);
    return localVarResponse.getData();
  }

  /**
   * Get income receipt by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param id  (required)
   * @param incomeId  (optional)
   * @return ApiResponse&lt;IncomeReceipt&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<IncomeReceipt> getIncomeReceiptByIdWithHttpInfo(String userId, String companyId, String jobId, String id, String incomeId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getIncomeReceiptByIdRequestBuilder(userId, companyId, jobId, id, incomeId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getIncomeReceiptById", localVarResponse);
        }
        return new ApiResponse<IncomeReceipt>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<IncomeReceipt>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getIncomeReceiptByIdRequestBuilder(String userId, String companyId, String jobId, String id, String incomeId) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getIncomeReceiptById");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling getIncomeReceiptById");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling getIncomeReceiptById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getIncomeReceiptById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/jobs/{jobId}/incomes_receipts/{id}"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{jobId}", ApiClient.urlEncode(jobId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "income_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("income_id", incomeId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all income receipts
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param incomeId  (optional)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @return PaginatedResponse
   * @throws ApiException if fails to make API call
   */
  public PaginatedResponse getIncomeReceipts(String userId, String companyId, String jobId, String incomeId, Integer page, Integer pageSize) throws ApiException {
    ApiResponse<PaginatedResponse> localVarResponse = getIncomeReceiptsWithHttpInfo(userId, companyId, jobId, incomeId, page, pageSize);
    return localVarResponse.getData();
  }

  /**
   * Get all income receipts
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param incomeId  (optional)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @return ApiResponse&lt;PaginatedResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaginatedResponse> getIncomeReceiptsWithHttpInfo(String userId, String companyId, String jobId, String incomeId, Integer page, Integer pageSize) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getIncomeReceiptsRequestBuilder(userId, companyId, jobId, incomeId, page, pageSize);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getIncomeReceipts", localVarResponse);
        }
        return new ApiResponse<PaginatedResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<PaginatedResponse>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getIncomeReceiptsRequestBuilder(String userId, String companyId, String jobId, String incomeId, Integer page, Integer pageSize) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getIncomeReceipts");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling getIncomeReceipts");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling getIncomeReceipts");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/jobs/{jobId}/incomes_receipts"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{jobId}", ApiClient.urlEncode(jobId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "income_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("income_id", incomeId));
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "page_size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page_size", pageSize));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
