/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.demo.client.api;

import com.example.demo.client.invoker.ApiClient;
import com.example.demo.client.invoker.ApiException;
import com.example.demo.client.invoker.ApiResponse;
import com.example.demo.client.invoker.Pair;

import com.example.demo.client.model.BadRequestException;
import com.example.demo.client.model.CrupdateLoan;
import com.example.demo.client.model.InternalServerException;
import com.example.demo.client.model.Loan;
import com.example.demo.client.model.LoanStatus;
import com.example.demo.client.model.NotAuthorizedException;
import com.example.demo.client.model.ResourceNotFoundException;
import com.example.demo.client.model.TooManyRequestsException;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-09T23:21:50.737140530+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class LoanApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public LoanApi() {
    this(new ApiClient());
  }

  public LoanApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Create new loans or update existing ones
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param crupdateLoan  (required)
   * @return List&lt;Loan&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Loan> crupdateLoans(String compId, String jobId, String userId, List<CrupdateLoan> crupdateLoan) throws ApiException {
    ApiResponse<List<Loan>> localVarResponse = crupdateLoansWithHttpInfo(compId, jobId, userId, crupdateLoan);
    return localVarResponse.getData();
  }

  /**
   * Create new loans or update existing ones
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param crupdateLoan  (required)
   * @return ApiResponse&lt;List&lt;Loan&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Loan>> crupdateLoansWithHttpInfo(String compId, String jobId, String userId, List<CrupdateLoan> crupdateLoan) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = crupdateLoansRequestBuilder(compId, jobId, userId, crupdateLoan);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("crupdateLoans", localVarResponse);
        }
        return new ApiResponse<List<Loan>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<Loan>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder crupdateLoansRequestBuilder(String compId, String jobId, String userId, List<CrupdateLoan> crupdateLoan) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling crupdateLoans");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling crupdateLoans");
    }
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling crupdateLoans");
    }
    // verify the required parameter 'crupdateLoan' is set
    if (crupdateLoan == null) {
      throw new ApiException(400, "Missing the required parameter 'crupdateLoan' when calling crupdateLoans");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/job/{job_id}/user/{user_id}/loans"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{job_id}", ApiClient.urlEncode(jobId.toString()))
        .replace("{user_id}", ApiClient.urlEncode(userId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(crupdateLoan);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete loan by identifier
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param id  (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteLoanById(String compId, String jobId, String userId, String id) throws ApiException {
    deleteLoanByIdWithHttpInfo(compId, jobId, userId, id);
  }

  /**
   * Delete loan by identifier
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteLoanByIdWithHttpInfo(String compId, String jobId, String userId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteLoanByIdRequestBuilder(compId, jobId, userId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteLoanById", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteLoanByIdRequestBuilder(String compId, String jobId, String userId, String id) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling deleteLoanById");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling deleteLoanById");
    }
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling deleteLoanById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteLoanById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/job/{job_id}/user/{user_id}/loans/{id}"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{job_id}", ApiClient.urlEncode(jobId.toString()))
        .replace("{user_id}", ApiClient.urlEncode(userId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get loan by identifier
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param id  (required)
   * @return Loan
   * @throws ApiException if fails to make API call
   */
  public Loan getLoanById(String compId, String jobId, String userId, String id) throws ApiException {
    ApiResponse<Loan> localVarResponse = getLoanByIdWithHttpInfo(compId, jobId, userId, id);
    return localVarResponse.getData();
  }

  /**
   * Get loan by identifier
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;Loan&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Loan> getLoanByIdWithHttpInfo(String compId, String jobId, String userId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getLoanByIdRequestBuilder(compId, jobId, userId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getLoanById", localVarResponse);
        }
        return new ApiResponse<Loan>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Loan>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getLoanByIdRequestBuilder(String compId, String jobId, String userId, String id) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling getLoanById");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling getLoanById");
    }
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getLoanById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getLoanById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/job/{job_id}/user/{user_id}/loans/{id}"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{job_id}", ApiClient.urlEncode(jobId.toString()))
        .replace("{user_id}", ApiClient.urlEncode(userId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all loans
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @param description Filter loans by description, case is ignored (optional)
   * @param amount  (optional)
   * @param lender Filter loans by lender, case is ignored (optional)
   * @param status Filter loans by status (optional)
   * @return List&lt;Loan&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Loan> getLoans(String compId, String jobId, String userId, Integer page, Integer pageSize, String description, Integer amount, String lender, LoanStatus status) throws ApiException {
    ApiResponse<List<Loan>> localVarResponse = getLoansWithHttpInfo(compId, jobId, userId, page, pageSize, description, amount, lender, status);
    return localVarResponse.getData();
  }

  /**
   * Get all loans
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @param description Filter loans by description, case is ignored (optional)
   * @param amount  (optional)
   * @param lender Filter loans by lender, case is ignored (optional)
   * @param status Filter loans by status (optional)
   * @return ApiResponse&lt;List&lt;Loan&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Loan>> getLoansWithHttpInfo(String compId, String jobId, String userId, Integer page, Integer pageSize, String description, Integer amount, String lender, LoanStatus status) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getLoansRequestBuilder(compId, jobId, userId, page, pageSize, description, amount, lender, status);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getLoans", localVarResponse);
        }
        return new ApiResponse<List<Loan>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<Loan>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getLoansRequestBuilder(String compId, String jobId, String userId, Integer page, Integer pageSize, String description, Integer amount, String lender, LoanStatus status) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling getLoans");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling getLoans");
    }
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getLoans");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/job/{job_id}/user/{user_id}/loans"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{job_id}", ApiClient.urlEncode(jobId.toString()))
        .replace("{user_id}", ApiClient.urlEncode(userId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "page_size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page_size", pageSize));
    localVarQueryParameterBaseName = "description";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("description", description));
    localVarQueryParameterBaseName = "amount";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("amount", amount));
    localVarQueryParameterBaseName = "lender";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("lender", lender));
    localVarQueryParameterBaseName = "status";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("status", status));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
