/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.demo.client.api;

import com.example.demo.client.invoker.ApiClient;
import com.example.demo.client.invoker.ApiException;
import com.example.demo.client.invoker.ApiResponse;
import com.example.demo.client.invoker.Pair;

import com.example.demo.client.model.BadRequestException;
import com.example.demo.client.model.CrupdateLoanRepayment;
import com.example.demo.client.model.InternalServerException;
import com.example.demo.client.model.LoanRepayment;
import com.example.demo.client.model.NotAuthorizedException;
import com.example.demo.client.model.ResourceNotFoundException;
import com.example.demo.client.model.TooManyRequestsException;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-13T22:11:25.203502239+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class LoanRepaymentApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public LoanRepaymentApi() {
    this(new ApiClient());
  }

  public LoanRepaymentApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Create new loan repayments or update existing ones
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param crupdateLoanRepayment  (required)
   * @param loanId  (optional)
   * @return List&lt;LoanRepayment&gt;
   * @throws ApiException if fails to make API call
   */
  public List<LoanRepayment> crupdateLoanRepayments(String userId, String companyId, String jobId, List<CrupdateLoanRepayment> crupdateLoanRepayment, String loanId) throws ApiException {
    ApiResponse<List<LoanRepayment>> localVarResponse = crupdateLoanRepaymentsWithHttpInfo(userId, companyId, jobId, crupdateLoanRepayment, loanId);
    return localVarResponse.getData();
  }

  /**
   * Create new loan repayments or update existing ones
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param crupdateLoanRepayment  (required)
   * @param loanId  (optional)
   * @return ApiResponse&lt;List&lt;LoanRepayment&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<LoanRepayment>> crupdateLoanRepaymentsWithHttpInfo(String userId, String companyId, String jobId, List<CrupdateLoanRepayment> crupdateLoanRepayment, String loanId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = crupdateLoanRepaymentsRequestBuilder(userId, companyId, jobId, crupdateLoanRepayment, loanId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("crupdateLoanRepayments", localVarResponse);
        }
        return new ApiResponse<List<LoanRepayment>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<LoanRepayment>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder crupdateLoanRepaymentsRequestBuilder(String userId, String companyId, String jobId, List<CrupdateLoanRepayment> crupdateLoanRepayment, String loanId) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling crupdateLoanRepayments");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling crupdateLoanRepayments");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling crupdateLoanRepayments");
    }
    // verify the required parameter 'crupdateLoanRepayment' is set
    if (crupdateLoanRepayment == null) {
      throw new ApiException(400, "Missing the required parameter 'crupdateLoanRepayment' when calling crupdateLoanRepayments");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/jobs/{jobId}/loan_repayments"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{jobId}", ApiClient.urlEncode(jobId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "loan_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("loan_id", loanId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(crupdateLoanRepayment);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete loan repayment by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param id  (required)
   * @param loanId  (optional)
   * @throws ApiException if fails to make API call
   */
  public void deleteLoanRepaymentById(String userId, String companyId, String jobId, String id, String loanId) throws ApiException {
    deleteLoanRepaymentByIdWithHttpInfo(userId, companyId, jobId, id, loanId);
  }

  /**
   * Delete loan repayment by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param id  (required)
   * @param loanId  (optional)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteLoanRepaymentByIdWithHttpInfo(String userId, String companyId, String jobId, String id, String loanId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteLoanRepaymentByIdRequestBuilder(userId, companyId, jobId, id, loanId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteLoanRepaymentById", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteLoanRepaymentByIdRequestBuilder(String userId, String companyId, String jobId, String id, String loanId) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling deleteLoanRepaymentById");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling deleteLoanRepaymentById");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling deleteLoanRepaymentById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteLoanRepaymentById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/jobs/{jobId}/loan_repayments/{id}"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{jobId}", ApiClient.urlEncode(jobId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "loan_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("loan_id", loanId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get loan repayment by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param id  (required)
   * @param loanId  (optional)
   * @return LoanRepayment
   * @throws ApiException if fails to make API call
   */
  public LoanRepayment getLoanRepaymentById(String userId, String companyId, String jobId, String id, String loanId) throws ApiException {
    ApiResponse<LoanRepayment> localVarResponse = getLoanRepaymentByIdWithHttpInfo(userId, companyId, jobId, id, loanId);
    return localVarResponse.getData();
  }

  /**
   * Get loan repayment by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param id  (required)
   * @param loanId  (optional)
   * @return ApiResponse&lt;LoanRepayment&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<LoanRepayment> getLoanRepaymentByIdWithHttpInfo(String userId, String companyId, String jobId, String id, String loanId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getLoanRepaymentByIdRequestBuilder(userId, companyId, jobId, id, loanId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getLoanRepaymentById", localVarResponse);
        }
        return new ApiResponse<LoanRepayment>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<LoanRepayment>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getLoanRepaymentByIdRequestBuilder(String userId, String companyId, String jobId, String id, String loanId) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getLoanRepaymentById");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling getLoanRepaymentById");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling getLoanRepaymentById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getLoanRepaymentById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/jobs/{jobId}/loan_repayments/{id}"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{jobId}", ApiClient.urlEncode(jobId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "loan_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("loan_id", loanId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all loan repayments
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param loanId  (optional)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @return List&lt;LoanRepayment&gt;
   * @throws ApiException if fails to make API call
   */
  public List<LoanRepayment> getLoanRepayments(String userId, String companyId, String jobId, String loanId, Integer page, Integer pageSize) throws ApiException {
    ApiResponse<List<LoanRepayment>> localVarResponse = getLoanRepaymentsWithHttpInfo(userId, companyId, jobId, loanId, page, pageSize);
    return localVarResponse.getData();
  }

  /**
   * Get all loan repayments
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param loanId  (optional)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @return ApiResponse&lt;List&lt;LoanRepayment&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<LoanRepayment>> getLoanRepaymentsWithHttpInfo(String userId, String companyId, String jobId, String loanId, Integer page, Integer pageSize) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getLoanRepaymentsRequestBuilder(userId, companyId, jobId, loanId, page, pageSize);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getLoanRepayments", localVarResponse);
        }
        return new ApiResponse<List<LoanRepayment>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<LoanRepayment>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getLoanRepaymentsRequestBuilder(String userId, String companyId, String jobId, String loanId, Integer page, Integer pageSize) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getLoanRepayments");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling getLoanRepayments");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling getLoanRepayments");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/jobs/{jobId}/loan_repayments"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{jobId}", ApiClient.urlEncode(jobId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "loan_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("loan_id", loanId));
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "page_size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page_size", pageSize));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
