/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.demo.client.api;

import com.example.demo.client.invoker.ApiClient;
import com.example.demo.client.invoker.ApiException;
import com.example.demo.client.invoker.ApiResponse;
import com.example.demo.client.invoker.Pair;

import com.example.demo.client.model.BadRequestException;
import com.example.demo.client.model.CrupdateNotification;
import com.example.demo.client.model.InternalServerException;
import com.example.demo.client.model.NotAuthorizedException;
import com.example.demo.client.model.Notification;
import com.example.demo.client.model.ResourceNotFoundException;
import com.example.demo.client.model.TooManyRequestsException;
import com.example.demo.client.model.UnreadNotificationCountResponse;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-12T23:54:11.411467005+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class NotificationApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public NotificationApi() {
    this(new ApiClient());
  }

  public NotificationApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Create or update notifications
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param crupdateNotification  (required)
   * @return List&lt;Notification&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Notification> crupdateNotifications(String userId, String companyId, List<CrupdateNotification> crupdateNotification) throws ApiException {
    ApiResponse<List<Notification>> localVarResponse = crupdateNotificationsWithHttpInfo(userId, companyId, crupdateNotification);
    return localVarResponse.getData();
  }

  /**
   * Create or update notifications
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param crupdateNotification  (required)
   * @return ApiResponse&lt;List&lt;Notification&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Notification>> crupdateNotificationsWithHttpInfo(String userId, String companyId, List<CrupdateNotification> crupdateNotification) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = crupdateNotificationsRequestBuilder(userId, companyId, crupdateNotification);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("crupdateNotifications", localVarResponse);
        }
        return new ApiResponse<List<Notification>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<Notification>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder crupdateNotificationsRequestBuilder(String userId, String companyId, List<CrupdateNotification> crupdateNotification) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling crupdateNotifications");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling crupdateNotifications");
    }
    // verify the required parameter 'crupdateNotification' is set
    if (crupdateNotification == null) {
      throw new ApiException(400, "Missing the required parameter 'crupdateNotification' when calling crupdateNotifications");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/notifications"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(crupdateNotification);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete notification by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param id  (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteNotificationById(String userId, String companyId, String id) throws ApiException {
    deleteNotificationByIdWithHttpInfo(userId, companyId, id);
  }

  /**
   * Delete notification by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteNotificationByIdWithHttpInfo(String userId, String companyId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteNotificationByIdRequestBuilder(userId, companyId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteNotificationById", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteNotificationByIdRequestBuilder(String userId, String companyId, String id) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling deleteNotificationById");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling deleteNotificationById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteNotificationById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/notifications/{id}"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get notification by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param id  (required)
   * @return Notification
   * @throws ApiException if fails to make API call
   */
  public Notification getNotificationById(String userId, String companyId, String id) throws ApiException {
    ApiResponse<Notification> localVarResponse = getNotificationByIdWithHttpInfo(userId, companyId, id);
    return localVarResponse.getData();
  }

  /**
   * Get notification by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;Notification&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Notification> getNotificationByIdWithHttpInfo(String userId, String companyId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getNotificationByIdRequestBuilder(userId, companyId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getNotificationById", localVarResponse);
        }
        return new ApiResponse<Notification>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Notification>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getNotificationByIdRequestBuilder(String userId, String companyId, String id) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getNotificationById");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling getNotificationById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getNotificationById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/notifications/{id}"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all notifications for the current user
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @param read  (optional)
   * @param completed  (optional)
   * @return List&lt;Notification&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Notification> getNotifications(String userId, String companyId, Integer page, Integer pageSize, Boolean read, Boolean completed) throws ApiException {
    ApiResponse<List<Notification>> localVarResponse = getNotificationsWithHttpInfo(userId, companyId, page, pageSize, read, completed);
    return localVarResponse.getData();
  }

  /**
   * Get all notifications for the current user
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @param read  (optional)
   * @param completed  (optional)
   * @return ApiResponse&lt;List&lt;Notification&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Notification>> getNotificationsWithHttpInfo(String userId, String companyId, Integer page, Integer pageSize, Boolean read, Boolean completed) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getNotificationsRequestBuilder(userId, companyId, page, pageSize, read, completed);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getNotifications", localVarResponse);
        }
        return new ApiResponse<List<Notification>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<Notification>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getNotificationsRequestBuilder(String userId, String companyId, Integer page, Integer pageSize, Boolean read, Boolean completed) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getNotifications");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling getNotifications");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/notifications"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "page_size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page_size", pageSize));
    localVarQueryParameterBaseName = "read";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("read", read));
    localVarQueryParameterBaseName = "completed";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("completed", completed));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get unread notification count for the current user
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @return UnreadNotificationCountResponse
   * @throws ApiException if fails to make API call
   */
  public UnreadNotificationCountResponse getUnreadNotificationCount(String userId, String companyId) throws ApiException {
    ApiResponse<UnreadNotificationCountResponse> localVarResponse = getUnreadNotificationCountWithHttpInfo(userId, companyId);
    return localVarResponse.getData();
  }

  /**
   * Get unread notification count for the current user
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @return ApiResponse&lt;UnreadNotificationCountResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UnreadNotificationCountResponse> getUnreadNotificationCountWithHttpInfo(String userId, String companyId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getUnreadNotificationCountRequestBuilder(userId, companyId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getUnreadNotificationCount", localVarResponse);
        }
        return new ApiResponse<UnreadNotificationCountResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<UnreadNotificationCountResponse>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getUnreadNotificationCountRequestBuilder(String userId, String companyId) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getUnreadNotificationCount");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling getUnreadNotificationCount");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/notifications/unread_count"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Mark notification as completed
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param id  (required)
   * @return Notification
   * @throws ApiException if fails to make API call
   */
  public Notification markNotificationAsCompleted(String userId, String companyId, String id) throws ApiException {
    ApiResponse<Notification> localVarResponse = markNotificationAsCompletedWithHttpInfo(userId, companyId, id);
    return localVarResponse.getData();
  }

  /**
   * Mark notification as completed
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;Notification&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Notification> markNotificationAsCompletedWithHttpInfo(String userId, String companyId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = markNotificationAsCompletedRequestBuilder(userId, companyId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("markNotificationAsCompleted", localVarResponse);
        }
        return new ApiResponse<Notification>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Notification>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder markNotificationAsCompletedRequestBuilder(String userId, String companyId, String id) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling markNotificationAsCompleted");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling markNotificationAsCompleted");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling markNotificationAsCompleted");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/notifications/{id}/complete"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Mark notification as read
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param id  (required)
   * @return Notification
   * @throws ApiException if fails to make API call
   */
  public Notification markNotificationAsRead(String userId, String companyId, String id) throws ApiException {
    ApiResponse<Notification> localVarResponse = markNotificationAsReadWithHttpInfo(userId, companyId, id);
    return localVarResponse.getData();
  }

  /**
   * Mark notification as read
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;Notification&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Notification> markNotificationAsReadWithHttpInfo(String userId, String companyId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = markNotificationAsReadRequestBuilder(userId, companyId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("markNotificationAsRead", localVarResponse);
        }
        return new ApiResponse<Notification>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Notification>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder markNotificationAsReadRequestBuilder(String userId, String companyId, String id) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling markNotificationAsRead");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling markNotificationAsRead");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling markNotificationAsRead");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/notifications/{id}/read"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
