/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.demo.client.api;

import com.example.demo.client.invoker.ApiClient;
import com.example.demo.client.invoker.ApiException;
import com.example.demo.client.invoker.ApiResponse;
import com.example.demo.client.invoker.Pair;

import com.example.demo.client.model.BadRequestException;
import com.example.demo.client.model.CrupdatePurchase;
import com.example.demo.client.model.InternalServerException;
import com.example.demo.client.model.NotAuthorizedException;
import com.example.demo.client.model.Purchase;
import com.example.demo.client.model.ResourceNotFoundException;
import com.example.demo.client.model.TooManyRequestsException;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-28T20:56:47.212042276+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class PurchaseApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public PurchaseApi() {
    this(new ApiClient());
  }

  public PurchaseApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Create new purchases or update existing ones
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param crupdatePurchase  (required)
   * @return List&lt;Purchase&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Purchase> crupdatePurchases(String compId, String jobId, String userId, String expensesId, List<CrupdatePurchase> crupdatePurchase) throws ApiException {
    ApiResponse<List<Purchase>> localVarResponse = crupdatePurchasesWithHttpInfo(compId, jobId, userId, expensesId, crupdatePurchase);
    return localVarResponse.getData();
  }

  /**
   * Create new purchases or update existing ones
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param crupdatePurchase  (required)
   * @return ApiResponse&lt;List&lt;Purchase&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Purchase>> crupdatePurchasesWithHttpInfo(String compId, String jobId, String userId, String expensesId, List<CrupdatePurchase> crupdatePurchase) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = crupdatePurchasesRequestBuilder(compId, jobId, userId, expensesId, crupdatePurchase);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("crupdatePurchases", localVarResponse);
        }
        return new ApiResponse<List<Purchase>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<Purchase>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder crupdatePurchasesRequestBuilder(String compId, String jobId, String userId, String expensesId, List<CrupdatePurchase> crupdatePurchase) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling crupdatePurchases");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling crupdatePurchases");
    }
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling crupdatePurchases");
    }
    // verify the required parameter 'expensesId' is set
    if (expensesId == null) {
      throw new ApiException(400, "Missing the required parameter 'expensesId' when calling crupdatePurchases");
    }
    // verify the required parameter 'crupdatePurchase' is set
    if (crupdatePurchase == null) {
      throw new ApiException(400, "Missing the required parameter 'crupdatePurchase' when calling crupdatePurchases");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses/{expenses_id}/purchases"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{job_id}", ApiClient.urlEncode(jobId.toString()))
        .replace("{user_id}", ApiClient.urlEncode(userId.toString()))
        .replace("{expenses_id}", ApiClient.urlEncode(expensesId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(crupdatePurchase);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete purchase by identifier
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param id  (required)
   * @throws ApiException if fails to make API call
   */
  public void deletePurchaseById(String compId, String jobId, String userId, String expensesId, String id) throws ApiException {
    deletePurchaseByIdWithHttpInfo(compId, jobId, userId, expensesId, id);
  }

  /**
   * Delete purchase by identifier
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deletePurchaseByIdWithHttpInfo(String compId, String jobId, String userId, String expensesId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deletePurchaseByIdRequestBuilder(compId, jobId, userId, expensesId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deletePurchaseById", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deletePurchaseByIdRequestBuilder(String compId, String jobId, String userId, String expensesId, String id) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling deletePurchaseById");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling deletePurchaseById");
    }
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling deletePurchaseById");
    }
    // verify the required parameter 'expensesId' is set
    if (expensesId == null) {
      throw new ApiException(400, "Missing the required parameter 'expensesId' when calling deletePurchaseById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deletePurchaseById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses/{expenses_id}/purchases/{id}"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{job_id}", ApiClient.urlEncode(jobId.toString()))
        .replace("{user_id}", ApiClient.urlEncode(userId.toString()))
        .replace("{expenses_id}", ApiClient.urlEncode(expensesId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get purchase by identifier
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param id  (required)
   * @return Purchase
   * @throws ApiException if fails to make API call
   */
  public Purchase getPurchaseById(String compId, String jobId, String userId, String expensesId, String id) throws ApiException {
    ApiResponse<Purchase> localVarResponse = getPurchaseByIdWithHttpInfo(compId, jobId, userId, expensesId, id);
    return localVarResponse.getData();
  }

  /**
   * Get purchase by identifier
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;Purchase&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Purchase> getPurchaseByIdWithHttpInfo(String compId, String jobId, String userId, String expensesId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPurchaseByIdRequestBuilder(compId, jobId, userId, expensesId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPurchaseById", localVarResponse);
        }
        return new ApiResponse<Purchase>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<Purchase>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPurchaseByIdRequestBuilder(String compId, String jobId, String userId, String expensesId, String id) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling getPurchaseById");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling getPurchaseById");
    }
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getPurchaseById");
    }
    // verify the required parameter 'expensesId' is set
    if (expensesId == null) {
      throw new ApiException(400, "Missing the required parameter 'expensesId' when calling getPurchaseById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getPurchaseById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses/{expenses_id}/purchases/{id}"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{job_id}", ApiClient.urlEncode(jobId.toString()))
        .replace("{user_id}", ApiClient.urlEncode(userId.toString()))
        .replace("{expenses_id}", ApiClient.urlEncode(expensesId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all purchases
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @param expenseId  (optional)
   * @param supplierId Filter purchases by supplier id (optional)
   * @param isEquipment  (optional)
   * @return List&lt;Purchase&gt;
   * @throws ApiException if fails to make API call
   */
  public List<Purchase> getPurchases(String compId, String jobId, String userId, String expensesId, Integer page, Integer pageSize, String expenseId, String supplierId, Boolean isEquipment) throws ApiException {
    ApiResponse<List<Purchase>> localVarResponse = getPurchasesWithHttpInfo(compId, jobId, userId, expensesId, page, pageSize, expenseId, supplierId, isEquipment);
    return localVarResponse.getData();
  }

  /**
   * Get all purchases
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @param expenseId  (optional)
   * @param supplierId Filter purchases by supplier id (optional)
   * @param isEquipment  (optional)
   * @return ApiResponse&lt;List&lt;Purchase&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<Purchase>> getPurchasesWithHttpInfo(String compId, String jobId, String userId, String expensesId, Integer page, Integer pageSize, String expenseId, String supplierId, Boolean isEquipment) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPurchasesRequestBuilder(compId, jobId, userId, expensesId, page, pageSize, expenseId, supplierId, isEquipment);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPurchases", localVarResponse);
        }
        return new ApiResponse<List<Purchase>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<Purchase>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPurchasesRequestBuilder(String compId, String jobId, String userId, String expensesId, Integer page, Integer pageSize, String expenseId, String supplierId, Boolean isEquipment) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling getPurchases");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling getPurchases");
    }
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getPurchases");
    }
    // verify the required parameter 'expensesId' is set
    if (expensesId == null) {
      throw new ApiException(400, "Missing the required parameter 'expensesId' when calling getPurchases");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses/{expenses_id}/purchases"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{job_id}", ApiClient.urlEncode(jobId.toString()))
        .replace("{user_id}", ApiClient.urlEncode(userId.toString()))
        .replace("{expenses_id}", ApiClient.urlEncode(expensesId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "page_size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page_size", pageSize));
    localVarQueryParameterBaseName = "expense_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("expense_id", expenseId));
    localVarQueryParameterBaseName = "supplier_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("supplier_id", supplierId));
    localVarQueryParameterBaseName = "is_equipment";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("is_equipment", isEquipment));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
