/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.demo.client.api;

import com.example.demo.client.invoker.ApiClient;
import com.example.demo.client.invoker.ApiException;
import com.example.demo.client.invoker.ApiResponse;
import com.example.demo.client.invoker.Pair;

import com.example.demo.client.model.BadRequestException;
import com.example.demo.client.model.ConfirmEquipmentArrival;
import com.example.demo.client.model.CrupdateTravelEquipment;
import com.example.demo.client.model.InternalServerException;
import com.example.demo.client.model.NotAuthorizedException;
import com.example.demo.client.model.PaginatedResponse;
import com.example.demo.client.model.ResourceNotFoundException;
import com.example.demo.client.model.TooManyRequestsException;
import com.example.demo.client.model.TransportStatus;
import com.example.demo.client.model.TravelEquipment;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-18T03:48:50.102368263+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class TravelEquipmentApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public TravelEquipmentApi() {
    this(new ApiClient());
  }

  public TravelEquipmentApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Confirm arrival of travel equipment (ARRIVED, LOST or DAMAGED)
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param confirmEquipmentArrival  (required)
   * @return List&lt;TravelEquipment&gt;
   * @throws ApiException if fails to make API call
   */
  public List<TravelEquipment> confirmEquipmentArrival(String userId, String companyId, List<ConfirmEquipmentArrival> confirmEquipmentArrival) throws ApiException {
    ApiResponse<List<TravelEquipment>> localVarResponse = confirmEquipmentArrivalWithHttpInfo(userId, companyId, confirmEquipmentArrival);
    return localVarResponse.getData();
  }

  /**
   * Confirm arrival of travel equipment (ARRIVED, LOST or DAMAGED)
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param confirmEquipmentArrival  (required)
   * @return ApiResponse&lt;List&lt;TravelEquipment&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<TravelEquipment>> confirmEquipmentArrivalWithHttpInfo(String userId, String companyId, List<ConfirmEquipmentArrival> confirmEquipmentArrival) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = confirmEquipmentArrivalRequestBuilder(userId, companyId, confirmEquipmentArrival);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("confirmEquipmentArrival", localVarResponse);
        }
        return new ApiResponse<List<TravelEquipment>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<TravelEquipment>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder confirmEquipmentArrivalRequestBuilder(String userId, String companyId, List<ConfirmEquipmentArrival> confirmEquipmentArrival) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling confirmEquipmentArrival");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling confirmEquipmentArrival");
    }
    // verify the required parameter 'confirmEquipmentArrival' is set
    if (confirmEquipmentArrival == null) {
      throw new ApiException(400, "Missing the required parameter 'confirmEquipmentArrival' when calling confirmEquipmentArrival");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/travel_equipments/arrival"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(confirmEquipmentArrival);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Create new travel equipment or update existing ones
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param crupdateTravelEquipment  (required)
   * @return List&lt;TravelEquipment&gt;
   * @throws ApiException if fails to make API call
   */
  public List<TravelEquipment> crupdateTravelEquipment(String userId, String companyId, String jobId, List<CrupdateTravelEquipment> crupdateTravelEquipment) throws ApiException {
    ApiResponse<List<TravelEquipment>> localVarResponse = crupdateTravelEquipmentWithHttpInfo(userId, companyId, jobId, crupdateTravelEquipment);
    return localVarResponse.getData();
  }

  /**
   * Create new travel equipment or update existing ones
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param crupdateTravelEquipment  (required)
   * @return ApiResponse&lt;List&lt;TravelEquipment&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<TravelEquipment>> crupdateTravelEquipmentWithHttpInfo(String userId, String companyId, String jobId, List<CrupdateTravelEquipment> crupdateTravelEquipment) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = crupdateTravelEquipmentRequestBuilder(userId, companyId, jobId, crupdateTravelEquipment);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("crupdateTravelEquipment", localVarResponse);
        }
        return new ApiResponse<List<TravelEquipment>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<TravelEquipment>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder crupdateTravelEquipmentRequestBuilder(String userId, String companyId, String jobId, List<CrupdateTravelEquipment> crupdateTravelEquipment) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling crupdateTravelEquipment");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling crupdateTravelEquipment");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling crupdateTravelEquipment");
    }
    // verify the required parameter 'crupdateTravelEquipment' is set
    if (crupdateTravelEquipment == null) {
      throw new ApiException(400, "Missing the required parameter 'crupdateTravelEquipment' when calling crupdateTravelEquipment");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/jobs/{jobId}/travel_equipments"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{jobId}", ApiClient.urlEncode(jobId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(crupdateTravelEquipment);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete travel equipment by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param id  (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteTravelEquipmentById(String userId, String companyId, String jobId, String id) throws ApiException {
    deleteTravelEquipmentByIdWithHttpInfo(userId, companyId, jobId, id);
  }

  /**
   * Delete travel equipment by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteTravelEquipmentByIdWithHttpInfo(String userId, String companyId, String jobId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteTravelEquipmentByIdRequestBuilder(userId, companyId, jobId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteTravelEquipmentById", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteTravelEquipmentByIdRequestBuilder(String userId, String companyId, String jobId, String id) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling deleteTravelEquipmentById");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling deleteTravelEquipmentById");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling deleteTravelEquipmentById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteTravelEquipmentById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/jobs/{jobId}/travel_equipments/{id}"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{jobId}", ApiClient.urlEncode(jobId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all travel equipment
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @param travelId  (optional)
   * @param equipmentId  (optional)
   * @param quantity  (optional)
   * @param status  (optional)
   * @param arrivalLocation Filter travel equipment by associated travel&#39;s arrival warehouse id (optional)
   * @param arrivalDateMin Filter travel equipment by minimum arrival date (optional)
   * @param arrivalDateMax Filter travel equipment by maximum arrival date (optional)
   * @param notArrived Filter travel equipment that have not arrived yet (no arrival date or location) (optional)
   * @return PaginatedResponse
   * @throws ApiException if fails to make API call
   */
  public PaginatedResponse getTravelEquipment(String userId, String companyId, String jobId, Integer page, Integer pageSize, String travelId, String equipmentId, Integer quantity, TransportStatus status, String arrivalLocation, java.time.Instant arrivalDateMin, java.time.Instant arrivalDateMax, Boolean notArrived) throws ApiException {
    ApiResponse<PaginatedResponse> localVarResponse = getTravelEquipmentWithHttpInfo(userId, companyId, jobId, page, pageSize, travelId, equipmentId, quantity, status, arrivalLocation, arrivalDateMin, arrivalDateMax, notArrived);
    return localVarResponse.getData();
  }

  /**
   * Get all travel equipment
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @param travelId  (optional)
   * @param equipmentId  (optional)
   * @param quantity  (optional)
   * @param status  (optional)
   * @param arrivalLocation Filter travel equipment by associated travel&#39;s arrival warehouse id (optional)
   * @param arrivalDateMin Filter travel equipment by minimum arrival date (optional)
   * @param arrivalDateMax Filter travel equipment by maximum arrival date (optional)
   * @param notArrived Filter travel equipment that have not arrived yet (no arrival date or location) (optional)
   * @return ApiResponse&lt;PaginatedResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PaginatedResponse> getTravelEquipmentWithHttpInfo(String userId, String companyId, String jobId, Integer page, Integer pageSize, String travelId, String equipmentId, Integer quantity, TransportStatus status, String arrivalLocation, java.time.Instant arrivalDateMin, java.time.Instant arrivalDateMax, Boolean notArrived) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getTravelEquipmentRequestBuilder(userId, companyId, jobId, page, pageSize, travelId, equipmentId, quantity, status, arrivalLocation, arrivalDateMin, arrivalDateMax, notArrived);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getTravelEquipment", localVarResponse);
        }
        return new ApiResponse<PaginatedResponse>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<PaginatedResponse>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getTravelEquipmentRequestBuilder(String userId, String companyId, String jobId, Integer page, Integer pageSize, String travelId, String equipmentId, Integer quantity, TransportStatus status, String arrivalLocation, java.time.Instant arrivalDateMin, java.time.Instant arrivalDateMax, Boolean notArrived) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getTravelEquipment");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling getTravelEquipment");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling getTravelEquipment");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/jobs/{jobId}/travel_equipments"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{jobId}", ApiClient.urlEncode(jobId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "page_size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page_size", pageSize));
    localVarQueryParameterBaseName = "travel_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("travel_id", travelId));
    localVarQueryParameterBaseName = "equipment_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("equipment_id", equipmentId));
    localVarQueryParameterBaseName = "quantity";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("quantity", quantity));
    localVarQueryParameterBaseName = "status";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("status", status));
    localVarQueryParameterBaseName = "arrival_location";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("arrival_location", arrivalLocation));
    localVarQueryParameterBaseName = "arrival_date_min";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("arrival_date_min", arrivalDateMin));
    localVarQueryParameterBaseName = "arrival_date_max";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("arrival_date_max", arrivalDateMax));
    localVarQueryParameterBaseName = "not_arrived";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("not_arrived", notArrived));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get travel equipment by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param id  (required)
   * @return TravelEquipment
   * @throws ApiException if fails to make API call
   */
  public TravelEquipment getTravelEquipmentById(String userId, String companyId, String jobId, String id) throws ApiException {
    ApiResponse<TravelEquipment> localVarResponse = getTravelEquipmentByIdWithHttpInfo(userId, companyId, jobId, id);
    return localVarResponse.getData();
  }

  /**
   * Get travel equipment by identifier
   * 
   * @param userId  (required)
   * @param companyId  (required)
   * @param jobId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;TravelEquipment&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TravelEquipment> getTravelEquipmentByIdWithHttpInfo(String userId, String companyId, String jobId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getTravelEquipmentByIdRequestBuilder(userId, companyId, jobId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getTravelEquipmentById", localVarResponse);
        }
        return new ApiResponse<TravelEquipment>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<TravelEquipment>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getTravelEquipmentByIdRequestBuilder(String userId, String companyId, String jobId, String id) throws ApiException {
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getTravelEquipmentById");
    }
    // verify the required parameter 'companyId' is set
    if (companyId == null) {
      throw new ApiException(400, "Missing the required parameter 'companyId' when calling getTravelEquipmentById");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling getTravelEquipmentById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getTravelEquipmentById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/users/{userId}/companies/{companyId}/jobs/{jobId}/travel_equipments/{id}"
        .replace("{userId}", ApiClient.urlEncode(userId.toString()))
        .replace("{companyId}", ApiClient.urlEncode(companyId.toString()))
        .replace("{jobId}", ApiClient.urlEncode(jobId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
