/*
 * Company Management API
 * API CRUD pour la gestion des entreprises, chantiers, entrepôts, équipements, matériaux, mouvements financiers, dépenses, achats et frais de transport. Basée sur le schéma de base de données fourni. 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.example.demo.client.api;

import com.example.demo.client.invoker.ApiClient;
import com.example.demo.client.invoker.ApiException;
import com.example.demo.client.invoker.ApiResponse;
import com.example.demo.client.invoker.Pair;

import com.example.demo.client.model.BadRequestException;
import com.example.demo.client.model.CrupdateTravelMaterials;
import com.example.demo.client.model.InternalServerException;
import com.example.demo.client.model.NotAuthorizedException;
import com.example.demo.client.model.ResourceNotFoundException;
import com.example.demo.client.model.TooManyRequestsException;
import com.example.demo.client.model.TravelMaterials;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-20T07:38:02.725832860+03:00[Indian/Antananarivo]", comments = "Generator version: 7.6.0")
public class TravelMaterialsApi {
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public TravelMaterialsApi() {
    this(new ApiClient());
  }

  public TravelMaterialsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }

  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Create new travel materials or update existing ones
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param travelExpensesId  (required)
   * @param crupdateTravelMaterials  (required)
   * @return List&lt;TravelMaterials&gt;
   * @throws ApiException if fails to make API call
   */
  public List<TravelMaterials> crupdateTravelMaterials(String compId, String jobId, String userId, String expensesId, String travelExpensesId, List<CrupdateTravelMaterials> crupdateTravelMaterials) throws ApiException {
    ApiResponse<List<TravelMaterials>> localVarResponse = crupdateTravelMaterialsWithHttpInfo(compId, jobId, userId, expensesId, travelExpensesId, crupdateTravelMaterials);
    return localVarResponse.getData();
  }

  /**
   * Create new travel materials or update existing ones
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param travelExpensesId  (required)
   * @param crupdateTravelMaterials  (required)
   * @return ApiResponse&lt;List&lt;TravelMaterials&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<TravelMaterials>> crupdateTravelMaterialsWithHttpInfo(String compId, String jobId, String userId, String expensesId, String travelExpensesId, List<CrupdateTravelMaterials> crupdateTravelMaterials) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = crupdateTravelMaterialsRequestBuilder(compId, jobId, userId, expensesId, travelExpensesId, crupdateTravelMaterials);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("crupdateTravelMaterials", localVarResponse);
        }
        return new ApiResponse<List<TravelMaterials>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<TravelMaterials>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder crupdateTravelMaterialsRequestBuilder(String compId, String jobId, String userId, String expensesId, String travelExpensesId, List<CrupdateTravelMaterials> crupdateTravelMaterials) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling crupdateTravelMaterials");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling crupdateTravelMaterials");
    }
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling crupdateTravelMaterials");
    }
    // verify the required parameter 'expensesId' is set
    if (expensesId == null) {
      throw new ApiException(400, "Missing the required parameter 'expensesId' when calling crupdateTravelMaterials");
    }
    // verify the required parameter 'travelExpensesId' is set
    if (travelExpensesId == null) {
      throw new ApiException(400, "Missing the required parameter 'travelExpensesId' when calling crupdateTravelMaterials");
    }
    // verify the required parameter 'crupdateTravelMaterials' is set
    if (crupdateTravelMaterials == null) {
      throw new ApiException(400, "Missing the required parameter 'crupdateTravelMaterials' when calling crupdateTravelMaterials");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses/{expenses_id}/travel_expenses/{travel_expenses_id}/travel_materials"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{job_id}", ApiClient.urlEncode(jobId.toString()))
        .replace("{user_id}", ApiClient.urlEncode(userId.toString()))
        .replace("{expenses_id}", ApiClient.urlEncode(expensesId.toString()))
        .replace("{travel_expenses_id}", ApiClient.urlEncode(travelExpensesId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(crupdateTravelMaterials);
      localVarRequestBuilder.method("PUT", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete travel materials by identifier
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param travelExpensesId  (required)
   * @param id  (required)
   * @throws ApiException if fails to make API call
   */
  public void deleteTravelMaterialsById(String compId, String jobId, String userId, String expensesId, String travelExpensesId, String id) throws ApiException {
    deleteTravelMaterialsByIdWithHttpInfo(compId, jobId, userId, expensesId, travelExpensesId, id);
  }

  /**
   * Delete travel materials by identifier
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param travelExpensesId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> deleteTravelMaterialsByIdWithHttpInfo(String compId, String jobId, String userId, String expensesId, String travelExpensesId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteTravelMaterialsByIdRequestBuilder(compId, jobId, userId, expensesId, travelExpensesId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteTravelMaterialsById", localVarResponse);
        }
        return new ApiResponse<Void>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
            // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteTravelMaterialsByIdRequestBuilder(String compId, String jobId, String userId, String expensesId, String travelExpensesId, String id) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling deleteTravelMaterialsById");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling deleteTravelMaterialsById");
    }
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling deleteTravelMaterialsById");
    }
    // verify the required parameter 'expensesId' is set
    if (expensesId == null) {
      throw new ApiException(400, "Missing the required parameter 'expensesId' when calling deleteTravelMaterialsById");
    }
    // verify the required parameter 'travelExpensesId' is set
    if (travelExpensesId == null) {
      throw new ApiException(400, "Missing the required parameter 'travelExpensesId' when calling deleteTravelMaterialsById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteTravelMaterialsById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses/{expenses_id}/travel_expenses/{travel_expenses_id}/travel_materials/{id}"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{job_id}", ApiClient.urlEncode(jobId.toString()))
        .replace("{user_id}", ApiClient.urlEncode(userId.toString()))
        .replace("{expenses_id}", ApiClient.urlEncode(expensesId.toString()))
        .replace("{travel_expenses_id}", ApiClient.urlEncode(travelExpensesId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get all travel materials
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param travelExpensesId  (required)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @param travelId  (optional)
   * @return List&lt;TravelMaterials&gt;
   * @throws ApiException if fails to make API call
   */
  public List<TravelMaterials> getTravelMaterials(String compId, String jobId, String userId, String expensesId, String travelExpensesId, Integer page, Integer pageSize, String travelId) throws ApiException {
    ApiResponse<List<TravelMaterials>> localVarResponse = getTravelMaterialsWithHttpInfo(compId, jobId, userId, expensesId, travelExpensesId, page, pageSize, travelId);
    return localVarResponse.getData();
  }

  /**
   * Get all travel materials
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param travelExpensesId  (required)
   * @param page  (optional)
   * @param pageSize  (optional)
   * @param travelId  (optional)
   * @return ApiResponse&lt;List&lt;TravelMaterials&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<TravelMaterials>> getTravelMaterialsWithHttpInfo(String compId, String jobId, String userId, String expensesId, String travelExpensesId, Integer page, Integer pageSize, String travelId) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getTravelMaterialsRequestBuilder(compId, jobId, userId, expensesId, travelExpensesId, page, pageSize, travelId);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getTravelMaterials", localVarResponse);
        }
        return new ApiResponse<List<TravelMaterials>>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<List<TravelMaterials>>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getTravelMaterialsRequestBuilder(String compId, String jobId, String userId, String expensesId, String travelExpensesId, Integer page, Integer pageSize, String travelId) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling getTravelMaterials");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling getTravelMaterials");
    }
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getTravelMaterials");
    }
    // verify the required parameter 'expensesId' is set
    if (expensesId == null) {
      throw new ApiException(400, "Missing the required parameter 'expensesId' when calling getTravelMaterials");
    }
    // verify the required parameter 'travelExpensesId' is set
    if (travelExpensesId == null) {
      throw new ApiException(400, "Missing the required parameter 'travelExpensesId' when calling getTravelMaterials");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses/{expenses_id}/travel_expenses/{travel_expenses_id}/travel_materials"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{job_id}", ApiClient.urlEncode(jobId.toString()))
        .replace("{user_id}", ApiClient.urlEncode(userId.toString()))
        .replace("{expenses_id}", ApiClient.urlEncode(expensesId.toString()))
        .replace("{travel_expenses_id}", ApiClient.urlEncode(travelExpensesId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "page";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page", page));
    localVarQueryParameterBaseName = "page_size";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("page_size", pageSize));
    localVarQueryParameterBaseName = "travel_id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("travel_id", travelId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get travel materials by identifier
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param travelExpensesId  (required)
   * @param id  (required)
   * @return TravelMaterials
   * @throws ApiException if fails to make API call
   */
  public TravelMaterials getTravelMaterialsById(String compId, String jobId, String userId, String expensesId, String travelExpensesId, String id) throws ApiException {
    ApiResponse<TravelMaterials> localVarResponse = getTravelMaterialsByIdWithHttpInfo(compId, jobId, userId, expensesId, travelExpensesId, id);
    return localVarResponse.getData();
  }

  /**
   * Get travel materials by identifier
   * 
   * @param compId  (required)
   * @param jobId  (required)
   * @param userId  (required)
   * @param expensesId  (required)
   * @param travelExpensesId  (required)
   * @param id  (required)
   * @return ApiResponse&lt;TravelMaterials&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TravelMaterials> getTravelMaterialsByIdWithHttpInfo(String compId, String jobId, String userId, String expensesId, String travelExpensesId, String id) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getTravelMaterialsByIdRequestBuilder(compId, jobId, userId, expensesId, travelExpensesId, id);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getTravelMaterialsById", localVarResponse);
        }
        return new ApiResponse<TravelMaterials>(
          localVarResponse.statusCode(),
          localVarResponse.headers().map(),
          localVarResponse.body() == null ? null : memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<TravelMaterials>() {}) // closes the InputStream
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getTravelMaterialsByIdRequestBuilder(String compId, String jobId, String userId, String expensesId, String travelExpensesId, String id) throws ApiException {
    // verify the required parameter 'compId' is set
    if (compId == null) {
      throw new ApiException(400, "Missing the required parameter 'compId' when calling getTravelMaterialsById");
    }
    // verify the required parameter 'jobId' is set
    if (jobId == null) {
      throw new ApiException(400, "Missing the required parameter 'jobId' when calling getTravelMaterialsById");
    }
    // verify the required parameter 'userId' is set
    if (userId == null) {
      throw new ApiException(400, "Missing the required parameter 'userId' when calling getTravelMaterialsById");
    }
    // verify the required parameter 'expensesId' is set
    if (expensesId == null) {
      throw new ApiException(400, "Missing the required parameter 'expensesId' when calling getTravelMaterialsById");
    }
    // verify the required parameter 'travelExpensesId' is set
    if (travelExpensesId == null) {
      throw new ApiException(400, "Missing the required parameter 'travelExpensesId' when calling getTravelMaterialsById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getTravelMaterialsById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/companies/{comp_id}/job/{job_id}/user/{user_id}/expenses/{expenses_id}/travel_expenses/{travel_expenses_id}/travel_materials/{id}"
        .replace("{comp_id}", ApiClient.urlEncode(compId.toString()))
        .replace("{job_id}", ApiClient.urlEncode(jobId.toString()))
        .replace("{user_id}", ApiClient.urlEncode(userId.toString()))
        .replace("{expenses_id}", ApiClient.urlEncode(expensesId.toString()))
        .replace("{travel_expenses_id}", ApiClient.urlEncode(travelExpensesId.toString()))
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
